// apps/web/app/gallery/gallery-data.ts
// Chase Pierson Photography — print catalog
// Titles are evocative, not descriptive. The art speaks.

export interface GalleryPrint {
  id: string;
  title: string;
  slug: string;
  src: string;
  category: Category;
  year: number;
  aspect: 'panoramic' | 'landscape' | 'portrait' | 'square';
  priceRange: string;
  sizes: string[];
  edition: string;
  featured?: boolean;
}

export type Category =
  | 'landscape'
  | 'night'
  | 'infrared'
  | 'studio'
  | 'natchez'
  | 'aerial'
  | 'interior';

export const CATEGORIES = [
  { id: 'all' as const, label: 'All Work' },
  { id: 'landscape' as const, label: 'Landscape' },
  { id: 'aerial' as const, label: 'Aerial' },
  { id: 'night' as const, label: 'Night' },
  { id: 'infrared' as const, label: 'Infrared' },
  { id: 'studio' as const, label: 'Studio' },
  { id: 'interior' as const, label: 'Interior' },
  { id: 'natchez' as const, label: 'Natchez' },
];

export const GALLERY_PRINTS: GalleryPrint[] = [
  // ── TIER 1: Hero / Statement Pieces ──────────────────────────
  {
    id: 'p01',
    title: 'Glass House, Blue Hour',
    slug: 'glass-house-blue-hour',
    src: '/images/gallery/prints/glass-house-blue-hour.webp',
    category: 'night',
    year: 2020,
    aspect: 'landscape',
    priceRange: '$400 – $1,200',
    sizes: ['16x20', '24x36', '40x60'],
    edition: 'Open edition',
    featured: true,
  },
  {
    id: 'p02',
    title: 'Ashokan Reservoir, Last Light',
    slug: 'ashokan-reservoir-last-light',
    src: '/images/gallery/prints/ashokan-reservoir-last-light.webp',
    category: 'landscape',
    year: 2019,
    aspect: 'panoramic',
    priceRange: '$400 – $1,800',
    sizes: ['16x20', '24x36', '40x60'],
    edition: 'Open edition',
    featured: true,
  },
  {
    id: 'p03',
    title: 'October Town',
    slug: 'october-town',
    src: '/images/gallery/prints/october-town.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$400 – $1,500',
    sizes: ['16x20', '24x36', '40x60'],
    edition: 'Open edition',
    featured: true,
  },
  {
    id: 'p04',
    title: 'The Divide',
    slug: 'the-divide',
    src: '/images/gallery/prints/the-divide.webp',
    category: 'landscape',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$400 – $1,200',
    sizes: ['16x20', '24x36', '40x60'],
    edition: 'Open edition',
    featured: true,
  },
  {
    id: 'p05',
    title: 'Cathedral Weather',
    slug: 'cathedral-weather',
    src: '/images/gallery/prints/cathedral-weather.webp',
    category: 'landscape',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$400 – $1,500',
    sizes: ['16x20', '24x36', '40x60'],
    edition: 'Open edition',
    featured: true,
  },

  // ── TIER 2: Landscape & Aerial ───────────────────────────────
  {
    id: 'p06',
    title: 'Blue Mountain, Before Dawn',
    slug: 'blue-mountain-before-dawn',
    src: '/images/gallery/prints/blue-mountain-before-dawn.webp',
    category: 'landscape',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p07',
    title: 'Cooper Lake at Dusk',
    slug: 'cooper-lake-at-dusk',
    src: '/images/gallery/prints/cooper-lake-at-dusk.webp',
    category: 'landscape',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$150 – $900',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p08',
    title: 'Valley Fog, Morning',
    slug: 'valley-fog-morning',
    src: '/images/gallery/prints/valley-fog-morning.webp',
    category: 'landscape',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p09',
    title: 'Overlook Mountain',
    slug: 'overlook-mountain',
    src: '/images/gallery/prints/overlook-mountain.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $900',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p10',
    title: 'Hutchins Hill, Twilight',
    slug: 'hutchins-hill-twilight',
    src: '/images/gallery/prints/hutchins-hill-twilight.webp',
    category: 'landscape',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p11',
    title: 'Catskill Hollow',
    slug: 'catskill-hollow',
    src: '/images/gallery/prints/catskill-hollow.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $900',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p12',
    title: 'Arkville in October',
    slug: 'arkville-in-october',
    src: '/images/gallery/prints/arkville-in-october.webp',
    category: 'aerial',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p13',
    title: 'River Road, Golden Hour',
    slug: 'river-road-golden-hour',
    src: '/images/gallery/prints/river-road-golden-hour.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $900',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p14',
    title: 'The Lone Tree',
    slug: 'the-lone-tree',
    src: '/images/gallery/prints/the-lone-tree.webp',
    category: 'aerial',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p15',
    title: 'A-Frame in the Canopy',
    slug: 'a-frame-in-the-canopy',
    src: '/images/gallery/prints/a-frame-in-the-canopy.webp',
    category: 'aerial',
    year: 2020,
    aspect: 'landscape',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p16',
    title: 'Sickler Road, Summer',
    slug: 'sickler-road-summer',
    src: '/images/gallery/prints/sickler-road-summer.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p17',
    title: 'Willow Fields, B&W',
    slug: 'willow-fields-bw',
    src: '/images/gallery/prints/willow-fields-bw.webp',
    category: 'landscape',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },

  // ── TIER 3: Night & Starlight ────────────────────────────────
  {
    id: 'p18',
    title: 'Catskill Stars',
    slug: 'catskill-stars',
    src: '/images/gallery/prints/catskill-stars.webp',
    category: 'night',
    year: 2020,
    aspect: 'landscape',
    priceRange: '$200 – $900',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p19',
    title: 'Mountain After Dark',
    slug: 'mountain-after-dark',
    src: '/images/gallery/prints/mountain-after-dark.webp',
    category: 'night',
    year: 2020,
    aspect: 'landscape',
    priceRange: '$200 – $900',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p20',
    title: 'Under the Live Oaks',
    slug: 'under-the-live-oaks',
    src: '/images/processed/natchez-night-live-oaks.webp',
    category: 'night',
    year: 2024,
    aspect: 'landscape',
    priceRange: '$150 – $600',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p21',
    title: 'Neon Moon',
    slug: 'neon-moon',
    src: '/images/corridor/night-neon-moon-entrance.webp',
    category: 'night',
    year: 2024,
    aspect: 'landscape',
    priceRange: '$150 – $500',
    sizes: ['8x10', '16x20'],
    edition: 'Open edition',
  },

  // ── TIER 4: Infrared & Experimental ──────────────────────────
  {
    id: 'p22',
    title: 'Red River',
    slug: 'red-river',
    src: '/images/gallery/prints/red-river.webp',
    category: 'infrared',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$500 – $1,000',
    sizes: ['16x20', '24x36'],
    edition: 'Limited to 25',
  },
  {
    id: 'p23',
    title: 'Gorge, False Color',
    slug: 'gorge-false-color',
    src: '/images/gallery/prints/gorge-false-color.webp',
    category: 'infrared',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$500 – $1,000',
    sizes: ['16x20', '24x36'],
    edition: 'Limited to 25',
  },
  {
    id: 'p24',
    title: 'River Bend, Neon',
    slug: 'river-bend-neon',
    src: '/images/gallery/prints/river-bend-neon.webp',
    category: 'infrared',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$500 – $1,000',
    sizes: ['16x20', '24x36'],
    edition: 'Limited to 25',
  },
  {
    id: 'p25',
    title: 'Eagles Nest, Infrared',
    slug: 'eagles-nest-infrared',
    src: '/images/gallery/prints/eagles-nest-infrared.webp',
    category: 'infrared',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$500 – $1,200',
    sizes: ['16x20', '24x36', '40x60'],
    edition: 'Limited to 25',
  },
  {
    id: 'p26',
    title: 'Mountain Acid',
    slug: 'mountain-acid',
    src: '/images/gallery/prints/mountain-acid.webp',
    category: 'infrared',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$200 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Limited to 25',
  },
  {
    id: 'p27',
    title: 'Catskills, Processed',
    slug: 'catskills-processed',
    src: '/images/gallery/prints/catskills-processed.webp',
    category: 'infrared',
    year: 2020,
    aspect: 'panoramic',
    priceRange: '$150 – $600',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },

  // ── TIER 5: Aerial Abstract ──────────────────────────────────
  {
    id: 'p28',
    title: 'Canopy, Straight Down',
    slug: 'canopy-straight-down',
    src: '/images/gallery/prints/canopy-straight-down.webp',
    category: 'aerial',
    year: 2020,
    aspect: 'square',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p29',
    title: 'October from Above',
    slug: 'october-from-above',
    src: '/images/gallery/prints/october-from-above.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$150 – $800',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p30',
    title: 'Winter Branches, B&W',
    slug: 'winter-branches-bw',
    src: '/images/gallery/prints/winter-branches-bw.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'square',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p31',
    title: 'Yellow Canopy',
    slug: 'yellow-canopy',
    src: '/images/gallery/prints/yellow-canopy.webp',
    category: 'aerial',
    year: 2021,
    aspect: 'square',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },

  // ── TIER 6: Studio & Music ───────────────────────────────────
  {
    id: 'p32',
    title: 'The Control Room',
    slug: 'the-control-room',
    src: '/images/gallery/prints/the-control-room.webp',
    category: 'studio',
    year: 2022,
    aspect: 'landscape',
    priceRange: '$150 – $600',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p33',
    title: 'Slingerland Kit, Waiting',
    slug: 'slingerland-kit-waiting',
    src: '/images/gallery/prints/slingerland-kit-waiting.webp',
    category: 'studio',
    year: 2022,
    aspect: 'landscape',
    priceRange: '$150 – $500',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p34',
    title: 'Snare Detail',
    slug: 'snare-detail',
    src: '/images/gallery/prints/snare-detail.webp',
    category: 'studio',
    year: 2022,
    aspect: 'landscape',
    priceRange: '$150 – $400',
    sizes: ['8x10', '16x20'],
    edition: 'Open edition',
  },
  {
    id: 'p35',
    title: 'Brandon',
    slug: 'brandon',
    src: '/images/gallery/prints/brandon.webp',
    category: 'studio',
    year: 2022,
    aspect: 'landscape',
    priceRange: '$150 – $500',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p36',
    title: 'EQ at the Window',
    slug: 'eq-at-the-window',
    src: '/images/gallery/toddaexports-2.webp',
    category: 'studio',
    year: 2022,
    aspect: 'landscape',
    priceRange: '$150 – $400',
    sizes: ['8x10', '16x20'],
    edition: 'Open edition',
  },

  // ── TIER 7: Interior & Architectural ─────────────────────────
  {
    id: 'p37',
    title: 'The Good Dog',
    slug: 'the-good-dog',
    src: '/images/gallery/prints/the-good-dog.webp',
    category: 'interior',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$150 – $500',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p38',
    title: 'Kilim and Beams',
    slug: 'kilim-and-beams',
    src: '/images/gallery/prints/kilim-and-beams.webp',
    category: 'interior',
    year: 2020,
    aspect: 'landscape',
    priceRange: '$150 – $400',
    sizes: ['8x10', '16x20'],
    edition: 'Open edition',
  },
  {
    id: 'p39',
    title: 'Cricket Ridge, the Table',
    slug: 'cricket-ridge-the-table',
    src: '/images/gallery/prints/cricket-ridge-the-table.webp',
    category: 'interior',
    year: 2021,
    aspect: 'landscape',
    priceRange: '$150 – $500',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p40',
    title: 'Hermitage Crossroads',
    slug: 'hermitage-crossroads',
    src: '/images/gallery/prints/hermitage-crossroads.webp',
    category: 'landscape',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $500',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },

  // ── TIER 8: Natchez / Deep South (already in repo) ───────────
  {
    id: 'p41',
    title: 'Golden Hour, Natchez',
    slug: 'golden-hour-natchez',
    src: '/images/processed/natchez-golden-hour-02.webp',
    category: 'natchez',
    year: 2024,
    aspect: 'landscape',
    priceRange: '$150 – $600',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p42',
    title: 'The Bluff',
    slug: 'the-bluff',
    src: '/images/corridor/natchez-bluff-river-view.webp',
    category: 'natchez',
    year: 2024,
    aspect: 'landscape',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p43',
    title: 'The Road In',
    slug: 'the-road-in',
    src: '/images/processed/catskills-road-autumn.webp',
    category: 'landscape',
    year: 2023,
    aspect: 'landscape',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p44',
    title: 'Looking Up',
    slug: 'looking-up',
    src: '/images/gallery/meghanstrees-denoiseai-clear-2018-processed-photo.webp',
    category: 'landscape',
    year: 2018,
    aspect: 'square',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
  {
    id: 'p45',
    title: 'Delta Flatlands, B&W',
    slug: 'delta-flatlands-bw',
    src: '/images/gallery/landscape-bw-panoramic.webp',
    category: 'landscape',
    year: 2021,
    aspect: 'panoramic',
    priceRange: '$150 – $700',
    sizes: ['8x10', '16x20', '24x36'],
    edition: 'Open edition',
  },
];
