import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  philosophy: [
    {
      type: 'category',
      label: 'The Philosophy',
      collapsed: false,
      items: [
        'philosophy/what-is-outsider-economics',
        'philosophy/people-are-the-currency',
        'philosophy/the-extraction-trap',
        'philosophy/coordination-not-scale',
        'philosophy/the-federation-effect',
      ],
    },
  ],
  toolkit: [
    {
      type: 'category',
      label: 'The Toolkit',
      collapsed: false,
      items: [
        'toolkit/the-task-board',
        'toolkit/building-without-banks',
        'toolkit/the-directory',
        'toolkit/the-20-revolution',
        'toolkit/technology-sovereignty',
        'toolkit/shared-services',
      ],
    },
  ],
  caseStudies: [
    {
      type: 'category',
      label: 'Case Studies',
      collapsed: false,
      items: [
        'case-studies/index',
        {
          type: 'autogenerated',
          dirName: 'case-studies/volume-1',
        },
        {
          type: 'autogenerated',
          dirName: 'case-studies/volume-2',
        },
        {
          type: 'autogenerated',
          dirName: 'case-studies/volume-3',
        },
        {
          type: 'autogenerated',
          dirName: 'case-studies/corridor',
        },
      ],
    },
  ],
  resources: [
    {
      type: 'category',
      label: 'Deep South Resources',
      collapsed: false,
      items: [
        'resources/index',
        'resources/grants-and-funding',
        'resources/organizations',
        'resources/legal-frameworks',
        'resources/technology-tools',
      ],
    },
  ],
};

export default sidebars;
