#!/usr/bin/env python3
"""
Regenerate docs/router/QUEUE.md from queue.json.
Called by scripts/router/sync.sh.
"""
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
QUEUE = ROOT / "docs" / "router" / "queue.json"
MARKDOWN = ROOT / "docs" / "router" / "QUEUE.md"

with open(QUEUE) as f:
    data = json.load(f)

queue = data["queue"]
buckets = defaultdict(list)
for p in queue:
    buckets[p["status"]].append(p)

SYM = {"done": "✓", "running": "▸", "ready": "○", "blocked": "✕"}

lines = []
lines.append("# Hillbilly Dreams Agent Queue")
lines.append("")
lines.append(f"*Last sync: {data['_updated']}*")
lines.append("")
lines.append(
    f"Status counts: {len(buckets['done'])} done · "
    f"{len(buckets['running'])} running · "
    f"{len(buckets['ready'])} ready · "
    f"{len(buckets['blocked'])} blocked · "
    f"**{len(queue)} total**"
)
lines.append("")
lines.append("## How to use this")
lines.append("")
lines.append("```bash")
lines.append("bash scripts/router/status.sh                   # snapshot of state")
lines.append("bash scripts/router/next.sh                     # next ready (copies prompt to clipboard)")
lines.append("bash scripts/router/next.sh --id P04-press-seed # specific project")
lines.append("bash scripts/router/ship.sh <id>                # mark done; auto-unblocks dependents")
lines.append("bash scripts/router/block.sh <id> '<reason>'    # mark blocked")
lines.append("bash scripts/router/unblock.sh <id>             # mark ready")
lines.append("```")
lines.append("")
lines.append("Each project below is **paste-ready** — copy the prompt into a fresh Claude or Cursor session and the agent has everything it needs.")
lines.append("")
lines.append("---")
lines.append("")

for status in ["running", "ready", "blocked", "done"]:
    items = buckets.get(status, [])
    if not items:
        continue
    lines.append(f"## {SYM[status]} {status.title()} ({len(items)})")
    lines.append("")
    for p in items:
        owner = p.get("owner", "")
        est = p.get("estimated_minutes", "?")
        lines.append(f"### `{p['id']}` — {p['title']}")
        lines.append("")
        meta_parts = [
            f"**Owner:** {owner}",
            f"**Est:** ~{est} min",
        ]
        if p.get("blocked_by"):
            meta_parts.append(f"**Blocked by:** {p['blocked_by']}")
        if p.get("depends_on"):
            meta_parts.append(f"**Depends on:** {', '.join(p['depends_on'])}")
        if p.get("shipped_at"):
            meta_parts.append(f"**Shipped:** {p['shipped_at']}")
        lines.append(" · ".join(meta_parts))
        lines.append("")
        if status in ("ready", "running"):
            lines.append("<details><summary>Show prompt</summary>")
            lines.append("")
            lines.append("```")
            lines.append(p["prompt"])
            lines.append("```")
            lines.append("</details>")
            lines.append("")
    lines.append("")

lines.append("---")
lines.append("")
lines.append("*Generated by `scripts/router/sync.sh` from `docs/router/queue.json`. Do not edit this file directly — edit the JSON.*")

MARKDOWN.write_text("\n".join(lines))
print(f"✓ Synced {MARKDOWN.relative_to(ROOT)}")
