// Outsider Economics video content — narrative-driven, not formula-driven
// Each video tells a story with numbers that builds to a punchline

export interface VideoStory {
  id: string;
  label: string;
  beats: Array<{
    text: string;
    highlight?: string; // big number or phrase to emphasize
    delay?: number; // extra frames before this beat
  }>;
  punchline: string;
}

export const STORIES: VideoStory[] = [
  {
    id: 'extraction-rate',
    label: 'THE EXTRACTION TRAP',
    beats: [
      { text: 'You make $5,000 a month.' },
      { text: '$4,100 leaves your zip code\nin 30 days.', highlight: '$4,100' },
      { text: "That's 82 cents on every dollar.", highlight: '82%' },
      { text: "Chain stores. Subscriptions.\nMortgage servicers in another state." },
      { text: "It doesn't go far.\nIt just goes.", delay: 15 },
    ],
    punchline: "You're not broke.\nYou're being drained.",
  },
  {
    id: 'coordination-multiplier',
    label: 'THE COORDINATION PREMIUM',
    beats: [
      { text: 'A plumber bills $80 an hour.' },
      { text: 'A plumber who knows an electrician,\na carpenter, and a permit expediter?' },
      { text: 'That crew bills renovations.', highlight: '$360/hr' },
      { text: 'Same people. Same hours.', delay: 10 },
    ],
    punchline: '4.5× the value.\nCoordination is the multiplier\nnobody talks about.',
  },
  {
    id: '450k-formula',
    label: 'THE $450,000 SECRET',
    beats: [
      { text: 'Twenty people.' },
      { text: 'Twenty hours a month each.' },
      { text: 'Real skills. Plumbing. Code.\nBookkeeping. Carpentry.', delay: 10 },
      { text: 'Blended rate: $112.50 an hour.', highlight: '$112.50' },
      { text: '20 × 20 × $112.50', highlight: '$450,000/mo' },
    ],
    punchline: 'No bank. No grant.\nNo permission.',
  },
  {
    id: 'time-currency',
    label: 'TIME IS THE ONLY CURRENCY\nTHAT CAN\'T LEAVE TOWN',
    beats: [
      { text: 'Money leaves. Always.' },
      { text: "But your neighbor's Saturday?\nThat stays." },
      { text: 'One hour of plumbing\n= one hour of bookkeeping.' },
      { text: "No exchange rate.\nNo inflation.\nNo extraction.", delay: 10 },
    ],
    punchline: "The currency that\ncan't leave town.",
  },
  {
    id: 'dunbar-federation',
    label: 'FEDERATION, NOT SCALE',
    beats: [
      { text: 'Every org that scales past\n150 people' },
      { text: 'starts acting like the thing\nit was built to replace.' },
      { text: 'So don\'t scale.', delay: 15 },
      { text: 'Keep each pod 20–50 people.\nWire them together.' },
    ],
    punchline: "Don't scale.\nFederate.",
  },
  {
    id: 'velocity-multiplier',
    label: 'THE VELOCITY MULTIPLIER',
    beats: [
      { text: '$1 at the local shop.' },
      { text: 'Shop owner pays the barber.', highlight: '$2' },
      { text: 'Barber eats at the diner.', highlight: '$3' },
      { text: 'Diner tips the mechanic.', highlight: '$3.50' },
    ],
    punchline: 'Every dollar that stays\nis worth three and a half.',
  },
];

// Key stats for StatCounter videos
export interface StatEntry {
  id: string;
  target: number;
  prefix: string;
  suffix: string;
  label: string;
  source: string;
  decimals?: number;
}

export const STATS: StatEntry[] = [
  { id: 'stat-450k', target: 450000, prefix: '$', suffix: '/mo', label: 'Generated by 20 people\ntrading 20 hours', source: 'Dispatch 01: The $450,000 Secret' },
  { id: 'stat-82pct', target: 82, prefix: '', suffix: '%', label: 'Of every dollar leaves\nyour zip code in 30 days', source: 'Dispatch 02: The Extraction Trap' },
  { id: 'stat-4-5x', target: 4.5, prefix: '', suffix: '×', label: 'Value multiplier\nfrom coordination', source: 'Dispatch 03: The Coordination Premium', decimals: 1 },
  { id: 'stat-150', target: 150, prefix: '', suffix: '', label: "Dunbar's number\nMax effective group size", source: 'Dispatch 07: Federation, Not Scale' },
];

// Quotes for QuoteCard videos
export interface QuoteEntry {
  id: string;
  quote: string;
  attribution: string;
  chapterLabel: string;
}

export const QUOTES: QuoteEntry[] = [
  { id: 'quote-broke', quote: "You're not broke.\nYou're being drained.", attribution: 'Outsider Economics', chapterLabel: 'Dispatch 02' },
  { id: 'quote-saturday', quote: "Money leaves. Always.\nBut your neighbor's Saturday?\nThat stays.", attribution: 'Outsider Economics', chapterLabel: 'Dispatch 04' },
  { id: 'quote-permission', quote: "The bank isn't in the\nmoney business.\nThe bank is in the\npermission business.", attribution: 'Outsider Economics', chapterLabel: 'Dispatch 06' },
  { id: 'quote-federate', quote: "Don't scale.\nFederate.", attribution: 'Outsider Economics', chapterLabel: 'Dispatch 07' },
  { id: 'quote-offswitch', quote: "Every system you depend on\nhas an off switch.\nAnd you're not the one\nholding it.", attribution: 'Outsider Economics', chapterLabel: 'Dispatch 10' },
];
