import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function seedTouring() {
  console.log('Seeding touring data — corridor artists, venues, hotels, routes...')

  // ── Regional Artists ──
  const artists = [
    {
      name: 'Cedric Burnside',
      slug: 'cedric-burnside',
      genre: 'blues',
      city: 'Holly Springs',
      state: 'MS',
      bio: 'Grammy-winning hill country blues drummer and guitarist. Third generation — grandson of R.L. Burnside. One of the most important living blues artists.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $3K-8K. 200-cap headliner. Grammy winner. High priority booking target.',
    },
    {
      name: 'Jimbo Mathus',
      slug: 'jimbo-mathus',
      genre: 'blues',
      city: 'Clarksdale',
      state: 'MS',
      bio: 'Founder of Squirrel Nut Zippers. Americana/blues songwriter and multi-instrumentalist. Clarksdale resident, Ground Zero regular.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $2K-5K. Blues Room or 200-cap. Lives in Clarksdale — easy logistics.',
    },
    {
      name: 'Super Chikan',
      slug: 'super-chikan',
      genre: 'blues',
      city: 'Clarksdale',
      state: 'MS',
      bio: 'James "Super Chikan" Johnson. Quintessential Delta blues. Builds guitars from cigar boxes and gas cans. BMA winner.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $500-1,500. Blues Room perfect. Authentic Delta character.',
    },
    {
      name: 'Terry "Harmonica" Bean',
      slug: 'terry-harmonica-bean',
      genre: 'blues',
      city: 'Pontotoc',
      state: 'MS',
      bio: 'Real juke joint harmonica player. Raw, unfiltered Delta blues. Festival circuit regular.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $500-1,200. Blues Room. Authentic as it gets.',
    },
    {
      name: 'Deak Harp',
      slug: 'deak-harp',
      genre: 'blues',
      city: 'Clarksdale',
      state: 'MS',
      bio: 'Solo blues/slide guitar and harmonica. Street performer turned recording artist. YouTube following. Lives and breathes Clarksdale.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $300-800. Blues Room. Great street-to-stage story for content.',
    },
    {
      name: 'Victor Wainwright',
      slug: 'victor-wainwright',
      genre: 'blues',
      city: 'Memphis',
      state: 'TN',
      bio: 'Blues/boogie-woogie pianist and vocalist. BMA winner. High-energy performer with deep roots musicianship.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $3K-8K. 200-cap headliner. Monthly headliner candidate.',
    },
    {
      name: 'Ruthie Foster',
      slug: 'ruthie-foster',
      genre: 'folk',
      city: 'Austin',
      state: 'TX',
      bio: 'Soul/blues/folk vocalist. Multiple BMA nominations. Tours the corridor regularly from Austin.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $5K-15K. 200-cap special event. Quarterly headliner.',
    },
    {
      name: 'Tab Benoit',
      slug: 'tab-benoit',
      genre: 'blues',
      city: 'Houma',
      state: 'LA',
      bio: 'Blues/roots guitarist from Louisiana bayou country. BMA winner. Environmental activist. Draws well across the corridor.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee range: $5K-15K. 200-cap headliner. Louisiana circuit natural fit.',
    },
    {
      name: 'Todd Adelman',
      slug: 'todd-adelman',
      genre: 'country',
      city: 'Woodstock',
      state: 'NY',
      bio: 'Americana/roots singer-songwriter. 7 albums. Tape-based recording studio "The Woods" in the Catskills. Band (The Woodsmen) features sidemen from Steve Earle, Rosanne Cash, Iggy Pop.',
      contactEmail: 'todd@toddadelman.com',
      socialLinks: { website: 'https://toddadelman.com', instagram: 'https://instagram.com/todd.adelman', spotify: 'https://open.spotify.com/artist/4muaVLBY1iY6NgXw28O4Mg' },
      source: 'scouted',
      status: 'discovered',
      notes: 'Bearsville-to-Natchez pipeline candidate. Self-managed. Analog recording philosophy aligns with Big Muddy aesthetic. First Bearsville Creative artist relationship.',
    },
    {
      name: 'Amy Allen',
      slug: 'amy-allen-artist',
      genre: 'blues',
      city: 'Natchez',
      state: 'MS',
      bio: 'Vocalist and performer. Big Muddy Inn equity partner. The house band\'s first collaborator — solo artist who performs with the rhythm section.',
      source: 'rise-up',
      status: 'showcasing',
      notes: 'Internal artist. House band primary vocalist. No external booking fee.',
    },
    // ── Wave 2: 20 more regional artists (R&D April 2026) ──
    {
      name: 'Lucious Spiller',
      slug: 'lucious-spiller',
      genre: 'blues',
      city: 'Clarksdale',
      state: 'MS',
      bio: 'Juke joint institution. Played with Bo Diddly, Albert King, Eddie Clearwater. Living oral tradition of the Delta.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $500-1,500. Blues Room perfect. Book through Roger Stolle at Cat Head (roger@cathead.biz).',
    },
    {
      name: 'Eric Deaton',
      slug: 'eric-deaton',
      genre: 'blues',
      city: 'Clarksdale',
      state: 'MS',
      bio: 'Hill country blues. Grammy-nominated (Cedric Burnside\'s "I Be Trying"). Apprenticed under Junior Kimbrough and R.L. Burnside. Played with The Black Keys.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $800-2,000. Blues Room ideal. Website: ericdeatonmusic.com. Teaches blues workshops.',
    },
    {
      name: 'Lightnin\' Malcolm',
      slug: 'lightnin-malcolm',
      genre: 'blues',
      city: 'Holly Springs',
      state: 'MS',
      bio: 'Former duo partner with Cedric Burnside. Has performed with Robert Plant, Jimmy Buffett, Robert Cray, The Black Keys, Gary Clark Jr.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $1,000-3,000. Reunion show with Cedric = press gold. Website: lightninmalcolm.com.',
    },
    {
      name: 'Duwayne Burnside',
      slug: 'duwayne-burnside',
      genre: 'blues',
      city: 'Holly Springs',
      state: 'MS',
      bio: 'Grammy-nominated son of R.L. Burnside. Played second guitar for North Mississippi Allstars. Ran the Burnside Blues Cafe.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $1,000-2,500. Hill Country Blues residency series with Cedric + Lightnin\' Malcolm.',
    },
    {
      name: 'Bill Abel',
      slug: 'bill-abel',
      genre: 'blues',
      city: 'Belzoni',
      state: 'MS',
      bio: 'Raw gutbucket Delta blues. Learned from T-Model Ford, Cadillac John, Paul Jones. Has played Blues Rules Festival in Switzerland.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $300-1,000. Regular Tuesday night candidate. 2hrs from Natchez. Archival-grade recordings.',
    },
    {
      name: 'Eden Brent',
      slug: 'eden-brent',
      genre: 'blues',
      city: 'Greenville',
      state: 'MS',
      bio: 'Blues piano, boogie-woogie, soul. Protege of legendary Boogaloo Ames. Tours internationally. Runs Blues in the Schools workshops.',
      contactEmail: 'via Tina Terry Agency (tinaterryagency.com)',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,000-5,000. Solo piano fills the Blues Room. Greenville is 90min from Natchez. Book through Tina Terry Agency.',
    },
    {
      name: 'John Nemeth',
      slug: 'john-nemeth',
      genre: 'blues',
      city: 'Memphis',
      state: 'TN',
      bio: '5x Blues Music Award winner including 2024 Soul Blues Male Artist. Fronts The Love Light Orchestra. Memphis soul royalty.',
      contactEmail: 'staff@intrepidartists.com',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $3,000-7,500. Love Light Orchestra = signature event. Booking: Intrepid Artists, 704-358-4777.',
    },
    {
      name: 'Nikki Hill',
      slug: 'nikki-hill',
      genre: 'rock',
      city: 'Memphis',
      state: 'TN',
      bio: 'Powerhouse soul/R&B/rock vocalist. In the tradition of Tina Turner and Big Mama Thornton. Has lived in NOLA, Memphis, St. Louis — she IS the corridor.',
      contactEmail: 'staff@intrepidartists.com',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $3,000-7,500. 200-cap only — high energy. Booking: Intrepid Artists. Magazine cover material.',
    },
    {
      name: 'Aretta Woodruff',
      slug: 'aretta-woodruff',
      genre: 'gospel',
      city: 'Bessemer',
      state: 'AL',
      bio: 'Alabama Blues Hall of Fame inductee (2018). Gospel-soul vocalist. Supported by Music Maker Foundation.',
      contactEmail: 'musicmaker@musicmaker.org',
      contactPhone: '(205) 426-1400',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $500-2,000. Blues Room — gospel-soul transcendent. Birmingham 5hrs from Natchez.',
    },
    {
      name: 'Paul Thorn',
      slug: 'paul-thorn',
      genre: 'country',
      city: 'Tupelo',
      state: 'MS',
      bio: 'Americana/roots rock/blues/gospel. Son of a preacher, former professional boxer. Tupelo, MS born. Heavy national touring.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $10,000-25,000. STRETCH booking. 200-cap only. Massive draw. Book well in advance.',
    },
    {
      name: 'Watermelon Slim',
      slug: 'watermelon-slim',
      genre: 'blues',
      city: 'Clarksdale',
      state: 'MS',
      bio: 'Harvard-educated Vietnam vet turned truck driver turned bluesman. Multiple BMA wins. Now based in Clarksdale.',
      contactEmail: 'info@BMATours.com',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,500-5,000. Blues Room or 200-cap. Local Clarksdale. Booking: Blue Mountain Artists, 704-525-1559.',
    },
    {
      name: 'Reba Russell',
      slug: 'reba-russell',
      genre: 'blues',
      city: 'Germantown',
      state: 'TN',
      bio: 'Blues-rock bandleader. 8 albums. Tours US and Europe. Independent artist Big Muddy ecosystem is designed to support.',
      contactEmail: 'reba1russell1@gmail.com',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $1,500-3,500. Both venues. Memphis metro, 5hrs from Natchez.',
    },
    {
      name: 'Grady Champion',
      slug: 'grady-champion',
      genre: 'blues',
      city: 'Jackson',
      state: 'MS',
      bio: 'Winner of 26th International Blues Challenge. Grammy and BMA winner. Harmonica and vocals. Jackson, MS — 2hrs from Natchez.',
      contactEmail: 'mfrank@earwigmusic.com',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,000-5,000. Both venues. Booking: Michael Frank at Earwig Music, 773-262-0278.',
    },
    {
      name: 'Sharde Thomas & The Rising Stars Fife and Drum Band',
      slug: 'sharde-thomas-rising-stars',
      genre: 'folk',
      city: 'Coldwater',
      state: 'MS',
      bio: 'Grammy-nominated. Granddaughter of Otha Turner. African-American fife and drum — oldest surviving African musical tradition in America.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,000-5,000 (full band). 200-cap or outdoor. A cultural EVENT — exactly what makes Big Muddy different.',
    },
    {
      name: 'Mr. Sipp',
      slug: 'mr-sipp',
      genre: 'blues',
      city: 'McComb',
      state: 'MS',
      bio: 'Castro Coleman, "The Mississippi Blues Child." Gospel-trained. Toured Brazil, Hong Kong, Russia, Germany, Scotland. McComb is 80mi from Natchez.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,000-5,000. Both venues. CLOSEST artist to Natchez (80mi). Website: mrsipp.net/contact.',
    },
    {
      name: 'Ra\'Shad "The Blues Kid" McGill',
      slug: 'rashad-blues-kid',
      genre: 'blues',
      city: 'Laurel',
      state: 'MS',
      bio: '2nd place at 2025 International Blues Challenge. Alabama Blues Hall of Fame. Southern soul blues. Rise Up material.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $500-1,500. Blues Room Rise Up showcase. Website: rtbkblues.com. 3hrs from Natchez.',
    },
    {
      name: 'Jarekus Singleton',
      slug: 'jarekus-singleton',
      genre: 'blues',
      city: 'Clinton',
      state: 'MS',
      bio: 'Modern blues. Signed to Alligator Records. Scouted at 2013 IBC by Bruce Iglauer. Church-to-blues pipeline. Jackson Music Award winner.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $1,500-4,000. Both venues. Clinton is 2hrs from Natchez. Booking: Blue Mountain Artists.',
    },
    {
      name: 'Marquise Knox',
      slug: 'marquise-knox',
      genre: 'blues',
      city: 'St. Louis',
      state: 'MO',
      bio: 'Born 1991. Performed with B.B. King, Pinetop Perkins, Honeyboy Edwards. Toured with ZZ Top. Runs own label. 3 albums.',
      contactEmail: 'info@marquiseknoxblues.com',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $1,500-4,000. Both venues. Rise Up headliner material. 6hrs from Natchez but tours corridor.',
    },
    {
      name: 'Jontavious Willis',
      slug: 'jontavious-willis',
      genre: 'folk',
      city: 'Greenville',
      state: 'GA',
      bio: 'Grammy-nominated at 28. Mentored by Taj Mahal. Acoustic blues encyclopedia — guitar, harmonica, banjo. Opened for Taj Mahal and Keb\' Mo\'.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,000-5,000. Blues Room acoustic — transcendent. Website: jontaviouswillis.com. Tours Deep South constantly.',
    },
    {
      name: 'Bobby Rush',
      slug: 'bobby-rush',
      genre: 'blues',
      city: 'Jackson',
      state: 'MS',
      bio: 'Age 92. 3x Grammy winner. 16x BMA winner (56 nominations). Blues Hall of Fame. Chitlin\' circuit legend. Jackson, MS — 2hrs from Natchez.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $25,000-40,000. STRETCH. 200-cap only. Book through The Kurland Agency (agents@thekurlandagency.com). BOOK WHILE WE CAN.',
    },
    {
      name: 'Ghost Town Blues Band',
      slug: 'ghost-town-blues-band',
      genre: 'blues',
      city: 'Memphis',
      state: 'TN',
      bio: 'Progressive blues with horns and cigar box guitar. Album "Shine" debuted #1 Billboard Blues. 5x Blues Blast nominee. Tennessee Music Award winner.',
      source: 'scouted',
      status: 'discovered',
      notes: 'Fee: $2,500-6,000. 200-cap. Booking: Riggs Entertainment (riggsentertainmentllc.com). Young, high-energy, draws a crowd.',
    },
  ]

  for (const artist of artists) {
    await prisma.artist.upsert({
      where: { slug: artist.slug },
      update: { ...artist },
      create: { ...artist },
    })
  }
  console.log(`Seeded ${artists.length} artists`)

  // ── Touring Venues ──
  const venues = [
    {
      name: 'The Big Muddy Inn — Blues Room',
      slug: 'blues-room-natchez',
      city: 'Natchez',
      state: 'MS',
      capacity: 40,
      venueType: 'club',
      soundSystem: 'Intimate PA, monitors. Acoustic-friendly room.',
      backlineAvailable: 'Full backline: drums, bass amp, guitar amp, keys. House band gear.',
      loadInNotes: 'Ground level entry. Gear through side door.',
      greenRoom: true,
      greenRoomNotes: 'Inn rooms double as green rooms. Artists stay on-site.',
      sprinterAccess: true,
      parkingSpaces: 4,
      seasonalNotes: 'Year-round. Peak: Mar-May, Sep-Nov. Slow: Jul-Aug (heat).',
      notes: 'Home venue. House band residency. 3-4 shows/week target. Artists stay at the Inn — lodging included in the deal.',
      isPublic: true,
    },
    {
      name: 'Ground Zero Blues Club',
      slug: 'ground-zero-clarksdale',
      city: 'Clarksdale',
      state: 'MS',
      capacity: 250,
      venueType: 'club',
      soundSystem: 'Full PA, sound engineer on staff. Good monitoring.',
      backlineAvailable: 'Drums, bass amp. BYO guitar amps.',
      loadInNotes: 'Front door load-in. Street parking for van.',
      greenRoom: true,
      greenRoomNotes: 'Basic but functional backstage area.',
      sprinterAccess: true,
      parkingSpaces: 10,
      bookingContactName: 'Roger Stolle',
      bookingContactEmail: null,
      bookingContactPhone: null,
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: '70/30 after guarantee',
      seasonalNotes: 'Juke Joint Festival (April) is peak. Slow Jun-Aug.',
      notes: 'Morgan Freeman co-owned. Iconic Delta venue. Essential corridor stop.',
      isPublic: true,
    },
    {
      name: 'Red\'s Lounge',
      slug: 'reds-lounge-clarksdale',
      city: 'Clarksdale',
      state: 'MS',
      capacity: 60,
      venueType: 'juke_joint',
      soundSystem: 'Minimal. Bring your own small PA.',
      backlineAvailable: 'None. BYO everything.',
      loadInNotes: 'Tight space. Front door only.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 3,
      typicalGuaranteeLow: 10000,
      typicalGuaranteeHigh: 50000,
      doorDealTerms: 'Door split or flat fee',
      seasonalNotes: 'Open when Big Red feels like it. Call ahead.',
      notes: 'Real juke joint. No frills. Incredible content opportunity. The authenticity is the point.',
      isPublic: true,
    },
    {
      name: 'Lafayette\'s Music Room',
      slug: 'lafayettes-memphis',
      city: 'Memphis',
      state: 'TN',
      capacity: 200,
      venueType: 'club',
      soundSystem: 'Full PA, in-house sound engineer. Excellent acoustics.',
      backlineAvailable: 'Full backline available. Call ahead.',
      loadInNotes: 'Side alley load-in. Covered.',
      greenRoom: true,
      greenRoomNotes: 'Proper green room with catering area.',
      sprinterAccess: true,
      parkingSpaces: 6,
      typicalGuaranteeLow: 100000,
      typicalGuaranteeHigh: 300000,
      doorDealTerms: '80/20 after guarantee',
      seasonalNotes: 'Year-round. Beale St. tourism drives walk-in traffic.',
      notes: 'Overton Square. Good listening room. Memphis corridor anchor.',
      isPublic: true,
    },
    {
      name: 'B.B. King\'s Blues Club',
      slug: 'bb-kings-memphis',
      city: 'Memphis',
      state: 'TN',
      capacity: 400,
      venueType: 'club',
      soundSystem: 'Full production PA. Multiple stages.',
      backlineAvailable: 'Full backline. Professional setup.',
      loadInNotes: 'Beale Street load-in. Restricted hours for truck access.',
      greenRoom: true,
      greenRoomNotes: 'Full backstage with dressing rooms.',
      sprinterAccess: false,
      parkingSpaces: 0,
      typicalGuaranteeLow: 200000,
      typicalGuaranteeHigh: 500000,
      doorDealTerms: 'Guarantee vs percentage, whichever is greater',
      seasonalNotes: 'Tourist season Mar-Oct. Memphis in May (festival) is peak.',
      notes: 'Iconic venue. Higher guarantee but high foot traffic. Special event only for us at current scale.',
      isPublic: true,
    },
  ]

  // ── NEW: Full Corridor Venues (13 cities, NOLA to Memphis) ──
  const corridorVenues = [
    // ── NEW ORLEANS ──
    {
      name: "Tipitina's",
      slug: 'tipitinas-nola',
      city: 'New Orleans',
      state: 'LA',
      address: '501 Napoleon Ave, New Orleans, LA 70115',
      capacity: 800,
      venueType: 'club',
      soundSystem: 'Full production PA. Professional sound and light rig. Projection screens available.',
      backlineAvailable: 'Full backline available. Call ahead to confirm.',
      loadInNotes: 'Street level load-in. Napoleon Ave access.',
      greenRoom: true,
      greenRoomNotes: 'Proper backstage area with dressing rooms.',
      sprinterAccess: true,
      parkingSpaces: 6,
      bookingContactName: 'Jeremy Smith (Special Events)',
      bookingContactEmail: 'Info@Tipitinas.com',
      bookingContactPhone: '504-895-8477',
      typicalGuaranteeLow: 200000,
      typicalGuaranteeHigh: 500000,
      doorDealTerms: 'Guarantee vs percentage. Negotiable for reciprocal.',
      seasonalNotes: 'Year-round. Jazz Fest (late Apr/early May) is peak. Mardi Gras season busy.',
      notes: 'NOLA institution since 1977. Anchor venue for corridor south end. Reciprocal booking target.',
      isPublic: true,
    },
    {
      name: 'Blue Nile',
      slug: 'blue-nile-nola',
      city: 'New Orleans',
      state: 'LA',
      address: '532 Frenchmen St, New Orleans, LA 70116',
      capacity: 290,
      venueType: 'club',
      soundSystem: 'Full PA. Two stages (upstairs and downstairs).',
      backlineAvailable: 'Basic backline. Call ahead.',
      loadInNotes: 'Frenchmen Street access. Street-level load-in.',
      greenRoom: true,
      greenRoomNotes: 'Backstage area available.',
      sprinterAccess: false,
      parkingSpaces: 0,
      bookingContactEmail: 'booking@bluenilelive.com',
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: 'Door split typical for touring acts.',
      seasonalNotes: 'Year-round. Frenchmen Street foot traffic drives walk-ins.',
      notes: 'Heart of Frenchmen Street. Funk, blues, soul, brass. Two stages. Great for mid-level acts.',
      isPublic: true,
    },
    {
      name: 'Snug Harbor Jazz Bistro',
      slug: 'snug-harbor-nola',
      city: 'New Orleans',
      state: 'LA',
      address: '626 Frenchmen St, New Orleans, LA 70116',
      capacity: 100,
      venueType: 'club',
      soundSystem: 'Intimate listening room PA. Excellent acoustics.',
      backlineAvailable: 'Piano on stage. BYO other instruments.',
      loadInNotes: 'Two-floor venue. Stage downstairs, mezzanine upstairs.',
      greenRoom: false,
      sprinterAccess: false,
      parkingSpaces: 0,
      bookingContactEmail: 'shows@snugjazz.com',
      bookingContactPhone: '504-949-0696',
      typicalGuaranteeLow: 30000,
      typicalGuaranteeHigh: 100000,
      doorDealTerms: 'Ticket sales split. Two sets per night (7:30pm & 9:30pm).',
      seasonalNotes: 'Year-round. 7 nights/week depending on season.',
      notes: 'Premier jazz listening room. 30+ years. Creole cuisine + jazz. Intimate Blues Room equivalent in NOLA.',
      isPublic: true,
    },
    // ── BATON ROUGE ──
    {
      name: 'The Varsity Theatre',
      slug: 'varsity-theatre-baton-rouge',
      city: 'Baton Rouge',
      state: 'LA',
      address: '3353 Highland Rd, Baton Rouge, LA 70802',
      capacity: 800,
      venueType: 'theater',
      soundSystem: 'Professional sound and light rig. Projection screens. Full production.',
      backlineAvailable: 'Full backline available for touring acts.',
      loadInNotes: 'Converted art deco theater near LSU. Stage load-in from rear.',
      greenRoom: true,
      greenRoomNotes: 'Backstage dressing rooms. Balcony holds 100.',
      sprinterAccess: true,
      parkingSpaces: 8,
      bookingContactEmail: null,
      typicalGuaranteeLow: 100000,
      typicalGuaranteeHigh: 400000,
      doorDealTerms: 'Negotiable. Mix of guarantee and percentage.',
      seasonalNotes: 'LSU calendar drives traffic. Football season (Sep-Nov) is peak.',
      notes: 'Converted art deco cinema near LSU. Professional touring venue. Good for 200-800 cap acts.',
      isPublic: true,
    },
    {
      name: "Teddy's Juke Joint",
      slug: 'teddys-juke-joint-zachary',
      city: 'Zachary',
      state: 'LA',
      address: '16999 Old Scenic Hwy, Zachary, LA 70791',
      capacity: 80,
      venueType: 'juke_joint',
      soundSystem: 'Basic PA. Authentic juke joint setup.',
      backlineAvailable: 'Minimal. BYO preferred.',
      loadInNotes: 'Rural location. Easy parking in fields. Outskirts of Baton Rouge.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 20,
      typicalGuaranteeLow: 10000,
      typicalGuaranteeHigh: 50000,
      doorDealTerms: 'Door split or flat fee. Cash business.',
      seasonalNotes: 'International and regional blues acts 2-4 nights/week.',
      notes: 'Opened 1979 by Teddy Johnson. Real juke joint among fields and farmlands. Nancy\'s Kitchen on-site serves incredible food. Content gold.',
      isPublic: true,
    },
    // ── VICKSBURG ──
    {
      name: 'Bottleneck Blues Bar',
      slug: 'bottleneck-blues-vicksburg',
      city: 'Vicksburg',
      state: 'MS',
      address: '4146 Washington St, Vicksburg, MS 39180',
      capacity: 200,
      venueType: 'club',
      soundSystem: 'Full PA. Casino venue production.',
      backlineAvailable: 'Available. Contact ahead.',
      loadInNotes: 'Inside Ameristar Casino. Casino loading dock access.',
      greenRoom: true,
      greenRoomNotes: 'Casino backstage facilities.',
      sprinterAccess: true,
      parkingSpaces: 50,
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: 'No cover charge typically. Casino pays guarantee.',
      seasonalNotes: 'Year-round. Fri-Sat shows at 8pm. Casino traffic is steady.',
      notes: 'Blues, R&B, soul, country. Inside Ameristar Casino. National and regional acts. Free shows = audience builder.',
      isPublic: true,
    },
    {
      name: 'Key City Brewery & The Roof at 1311',
      slug: 'key-city-brewery-vicksburg',
      city: 'Vicksburg',
      state: 'MS',
      address: '1311 Washington St, Vicksburg, MS 39183',
      capacity: 100,
      venueType: 'club',
      soundSystem: 'Basic PA. Rooftop venue sound setup.',
      backlineAvailable: 'Minimal. BYO.',
      loadInNotes: 'Downtown Vicksburg. Street-level access. Rooftop via elevator.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 5,
      typicalGuaranteeLow: 20000,
      typicalGuaranteeHigh: 80000,
      doorDealTerms: 'Door split or flat fee. Brewery revenue supplements.',
      seasonalNotes: 'Rooftop weather-dependent. Best Mar-Nov.',
      notes: 'Craft brewery + rooftop venue. Downtown Vicksburg. Good for acoustic/smaller acts. River views.',
      isPublic: true,
    },
    // ── JACKSON ──
    {
      name: "Hal & Mal's",
      slug: 'hal-and-mals-jackson',
      city: 'Jackson',
      state: 'MS',
      address: '200 S Commerce St, Jackson, MS 39201',
      capacity: 300,
      venueType: 'club',
      soundSystem: 'Full PA. Multiple rooms: dining room, red room, brew pub, The Big Room.',
      backlineAvailable: 'Basic backline. Call ahead.',
      loadInNotes: 'Street-level load-in. Commerce Street access.',
      greenRoom: true,
      greenRoomNotes: 'Backstage in The Big Room.',
      sprinterAccess: true,
      parkingSpaces: 10,
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: 'Negotiable. Blue Monday jam sessions are no-pay open format.',
      seasonalNotes: 'Year-round. Blue Monday (Central Blues Society) every Monday night.',
      notes: 'Jackson staple since 1985. Hal and Malcolm White. Multiple rooms for different size acts. Essential Jackson stop.',
      isPublic: true,
    },
    {
      name: 'F. Jones Corner',
      slug: 'f-jones-corner-jackson',
      city: 'Jackson',
      state: 'MS',
      address: '303 N Farish St, Jackson, MS 39202',
      capacity: 80,
      venueType: 'juke_joint',
      soundSystem: 'Basic PA. Intimate blues club setup.',
      backlineAvailable: 'Minimal. BYO.',
      loadInNotes: 'Historic 1923 building. Front door load-in. Farish Street.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 5,
      typicalGuaranteeLow: 10000,
      typicalGuaranteeHigh: 50000,
      doorDealTerms: 'Door split. Live blues Fri-Sat 12am-4am.',
      seasonalNotes: 'Late night venue. Fri-Sat midnight to 4am.',
      notes: 'Historic Farish Street blues club. Late night format (midnight-4am). Intimate, authentic. The real deal in Jackson.',
      isPublic: true,
    },
    {
      name: "Martin's Downtown",
      slug: 'martins-downtown-jackson',
      city: 'Jackson',
      state: 'MS',
      address: '214 S State St, Jackson, MS 39201',
      capacity: 150,
      venueType: 'club',
      soundSystem: 'Basic PA for live music.',
      backlineAvailable: 'Minimal.',
      loadInNotes: 'Across from Hal & Mal\'s. Street-level access.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 5,
      typicalGuaranteeLow: 20000,
      typicalGuaranteeHigh: 80000,
      doorDealTerms: 'Door split or flat fee.',
      seasonalNotes: 'Live music nearly every night. Blue Plate lunch specials.',
      notes: 'Restaurant + live music. Right across from Hal & Mal\'s. Full bar. Good pairing for Jackson double-header nights.',
      isPublic: true,
    },
    // ── GREENVILLE ──
    {
      name: 'Walnut Street Blues Bar',
      slug: 'walnut-street-blues-greenville',
      city: 'Greenville',
      state: 'MS',
      address: '128 S Walnut St, Greenville, MS 38701',
      capacity: 80,
      venueType: 'club',
      soundSystem: 'Basic PA. Blues club setup.',
      backlineAvailable: 'Minimal. BYO.',
      loadInNotes: 'Downtown Greenville. Street-level.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 5,
      typicalGuaranteeLow: 10000,
      typicalGuaranteeHigh: 50000,
      doorDealTerms: 'Door split. Open mic nights and guest performances.',
      seasonalNotes: 'Mon-Fri 5pm-2am, Sat 6pm-2am. Closed Sunday.',
      notes: 'Local blues showcase. Eden Brent territory. Intimate setting. Open mic nights + themed nights.',
      isPublic: true,
    },
    {
      name: 'The Blue Biscuit',
      slug: 'blue-biscuit-greenville',
      city: 'Greenville',
      state: 'MS',
      address: 'Greenville, MS 38701',
      capacity: 60,
      venueType: 'juke_joint',
      soundSystem: 'Basic. Authentic juke joint.',
      backlineAvailable: 'Minimal. BYO.',
      loadInNotes: 'Greenville Delta venue. Small space.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 5,
      typicalGuaranteeLow: 5000,
      typicalGuaranteeHigh: 30000,
      doorDealTerms: 'Door split or flat fee.',
      seasonalNotes: 'Weekend performances primarily.',
      notes: 'Laid-back juke joint atmosphere. Local and traveling blues musicians. Authentic Delta experience.',
      isPublic: true,
    },
    // ── GREENWOOD ──
    {
      name: 'Crystal Grill',
      slug: 'crystal-grill-greenwood',
      city: 'Greenwood',
      state: 'MS',
      address: '423 Carrollton Ave, Greenwood, MS 38930',
      capacity: 60,
      venueType: 'club',
      soundSystem: 'Minimal. Acoustic-friendly space.',
      backlineAvailable: 'None. BYO.',
      loadInNotes: 'Historic downtown Greenwood restaurant.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 5,
      typicalGuaranteeLow: 10000,
      typicalGuaranteeHigh: 30000,
      doorDealTerms: 'Flat fee for private events. Dinner + music format.',
      seasonalNotes: 'Robert Johnson territory. Crossroads guitar exhibit at museum (summer).',
      notes: 'Greenwood venue option. Robert Johnson crossroads territory. Baptist Town nearby. More of a dinner music format than a club.',
      isPublic: true,
    },
    // ── INDIANOLA ──
    {
      name: 'Club Ebony',
      slug: 'club-ebony-indianola',
      city: 'Indianola',
      state: 'MS',
      address: '404 Hannah Ave, Indianola, MS 38751',
      capacity: 250,
      venueType: 'club',
      soundSystem: 'Renovated PA system. Historic stage.',
      backlineAvailable: 'Basic. Contact B.B. King Museum staff.',
      loadInNotes: 'Adjacent to B.B. King Museum. Ground-level access.',
      greenRoom: true,
      greenRoomNotes: 'Renovated backstage area.',
      sprinterAccess: true,
      parkingSpaces: 15,
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: 'Coordinate through B.B. King Museum. Special events format.',
      seasonalNotes: 'Museum open Thu-Sat 10am-5pm. Club events scheduled separately.',
      notes: 'LEGENDARY. Est. 1948. B.B. King, Ray Charles, Count Basie played here. B.B. King purchased to preserve. Renovated 2023. Now part of B.B. King Museum complex. Hologram shows and live events.',
      isPublic: true,
    },
    // ── HOLLY SPRINGS ──
    {
      name: 'Burnside Bar and Grill',
      slug: 'burnside-bar-grill-holly-springs',
      city: 'Holly Springs',
      state: 'MS',
      address: 'Holly Springs, MS 38635',
      capacity: 60,
      venueType: 'juke_joint',
      soundSystem: 'Basic. Juke joint PA.',
      backlineAvailable: 'Minimal. BYO.',
      loadInNotes: 'Duwayne Burnside\'s venue in Junior Kimbrough\'s old building.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 10,
      typicalGuaranteeLow: 5000,
      typicalGuaranteeHigh: 30000,
      doorDealTerms: 'Door split. BBQ + blues format.',
      seasonalNotes: 'Weekly live blues + BBQ. Soft opened April 2022.',
      notes: 'Duwayne Burnside (R.L.\'s son) runs this in Junior Kimbrough\'s old juke joint building. Hill Country Blues ground zero. BBQ + blues. Content goldmine.',
      isPublic: true,
    },
    // ── TUPELO ──
    {
      name: 'Blue Canoe',
      slug: 'blue-canoe-tupelo',
      city: 'Tupelo',
      state: 'MS',
      address: '2006 N Gloster St, Tupelo, MS 38804',
      capacity: 150,
      venueType: 'club',
      soundSystem: 'Full PA. Good live sound setup for touring acts.',
      backlineAvailable: 'Basic. Call ahead.',
      loadInNotes: 'Street-level. Easy parking lot access.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 15,
      bookingContactPhone: '662-269-2642',
      typicalGuaranteeLow: 30000,
      typicalGuaranteeHigh: 150000,
      doorDealTerms: 'Guarantee + door split for national acts.',
      seasonalNotes: 'Weekend shows 8:30pm (21+). Weekday shows 7:30pm (all ages). Closed Sundays.',
      notes: 'Tupelo\'s live music anchor since 2011. Has hosted Gary Clark Jr., Alabama Shakes. 100+ beers. Top 10 burger in MS. Paul Thorn territory.',
      isPublic: true,
    },
    {
      name: 'Backline Music Hall',
      slug: 'backline-music-hall-tupelo',
      city: 'Tupelo',
      state: 'MS',
      address: 'Tupelo, MS 38801',
      capacity: 300,
      venueType: 'club',
      soundSystem: 'Full production PA. New venue build-out.',
      backlineAvailable: 'Full backline available.',
      loadInNotes: 'New venue. Good load-in facilities.',
      greenRoom: true,
      sprinterAccess: true,
      parkingSpaces: 15,
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: 'Negotiable. Mix of guarantee and percentage.',
      seasonalNotes: 'Tupelo\'s newest venue. Touring and regional acts.',
      notes: 'Newest Tupelo venue. Touring acts + local/regional talent. Good mid-size room.',
      isPublic: true,
    },
    // ── OXFORD ──
    {
      name: "Proud Larry's",
      slug: 'proud-larrys-oxford',
      city: 'Oxford',
      state: 'MS',
      address: '211 S Lamar Blvd, Oxford, MS 38655',
      capacity: 300,
      venueType: 'club',
      soundSystem: 'Full PA. Professional sound for touring acts.',
      backlineAvailable: 'Available. Contact ahead.',
      loadInNotes: 'Just off the Square. Street-level.',
      greenRoom: true,
      sprinterAccess: true,
      parkingSpaces: 5,
      bookingContactEmail: 'talent@proudlarrys.com',
      bookingContactPhone: '662-236-0050',
      typicalGuaranteeLow: 50000,
      typicalGuaranteeHigh: 200000,
      doorDealTerms: 'Guarantee + percentage. 18+ shows available.',
      seasonalNotes: 'Ole Miss calendar drives traffic. Football season (Sep-Nov) is peak. Tuesdays reserved for residencies.',
      notes: 'Oxford staple for 20+ years. Restaurant + music venue. Off the Square. Great for 100-300 cap touring acts. Ole Miss student base.',
      isPublic: true,
    },
    {
      name: 'The Lyric Oxford',
      slug: 'lyric-oxford',
      city: 'Oxford',
      state: 'MS',
      address: '1006 Van Buren Ave, Oxford, MS 38655',
      capacity: 1000,
      venueType: 'theater',
      soundSystem: 'Full production PA. Historic theater acoustics.',
      backlineAvailable: 'Full backline available.',
      loadInNotes: 'Off the Square. Corner of Van Buren & 11th. No parking lot — street parking only.',
      greenRoom: true,
      greenRoomNotes: 'Backstage dressing rooms.',
      sprinterAccess: true,
      parkingSpaces: 0,
      bookingContactName: 'Scott',
      bookingContactEmail: 'scott@thelyricoxford.com',
      bookingContactPhone: '662-234-5333',
      typicalGuaranteeLow: 200000,
      typicalGuaranteeHigh: 500000,
      doorDealTerms: 'Guarantee + ticket percentage.',
      seasonalNotes: 'Year-round. Concerts, fundraisers, private events, weddings.',
      notes: 'Founded 1913 as silent movie theater. Oxford\'s premier live event space. 1,000 standing. Concerts + events. Bigger room for headliners.',
      isPublic: true,
    },
    // ── MEMPHIS (additions) ──
    {
      name: 'Hi-Tone',
      slug: 'hi-tone-memphis',
      city: 'Memphis',
      state: 'TN',
      address: '282-284 N Cleveland St, Memphis, TN 38104',
      capacity: 400,
      venueType: 'club',
      soundSystem: 'Full PA. Two distinct performance spaces.',
      backlineAvailable: 'Basic. BYO preferred.',
      loadInNotes: 'Street-level. Cleveland Street access. Midtown location.',
      greenRoom: true,
      greenRoomNotes: 'Backstage area available.',
      sprinterAccess: true,
      parkingSpaces: 8,
      bookingContactPhone: '901-490-0335',
      typicalGuaranteeLow: 30000,
      typicalGuaranteeHigh: 150000,
      doorDealTerms: 'Door split typical. Negotiable for touring acts.',
      seasonalNotes: 'Year-round. Open 5pm-3am daily. Memphis in May (festival) peak.',
      notes: 'Memphis indie/rock/blues institution since 1999. Two rooms — larger main room + intimate downstairs. Has hosted Ryan Adams, Elvis Costello. Diverse genres.',
      isPublic: true,
    },
    {
      name: 'Young Avenue Deli',
      slug: 'young-ave-deli-memphis',
      city: 'Memphis',
      state: 'TN',
      address: '2119 Young Ave, Memphis, TN 38104',
      capacity: 200,
      venueType: 'club',
      soundSystem: 'Basic PA. Bar venue setup.',
      backlineAvailable: 'Minimal. BYO.',
      loadInNotes: 'Midtown Memphis. Cooper-Young neighborhood. Easy access.',
      greenRoom: false,
      sprinterAccess: true,
      parkingSpaces: 8,
      typicalGuaranteeLow: 20000,
      typicalGuaranteeHigh: 100000,
      doorDealTerms: 'Door split.',
      seasonalNotes: 'Year-round. Late night dining + music.',
      notes: 'Cooper-Young neighborhood. Live music, pool tables, full-service late night dining. Good for smaller acts or after-show hangout.',
      isPublic: true,
    },
  ]

  // Merge existing venues + new corridor venues
  const allVenues = [...venues, ...corridorVenues]

  for (const venue of allVenues) {
    await prisma.touringVenue.upsert({
      where: { slug: venue.slug },
      update: { ...venue },
      create: { ...venue },
    })
  }
  console.log(`Seeded ${allVenues.length} touring venues (${venues.length} existing + ${corridorVenues.length} new corridor)`)

  // ── Touring Hotels ──
  const hotels = [
    {
      name: 'Shack Up Inn',
      city: 'Clarksdale',
      state: 'MS',
      rateLow: 7500,
      rateHigh: 15000,
      roomCount: 12,
      amenities: ['wifi', 'parking', 'kitchen', 'porch'],
      bandFriendly: true,
      bandFriendlyNotes: 'Built for musicians. Shotgun shacks and grain bins converted to rooms. Late night friendly.',
      sprinterParking: true,
      notes: 'THE musician hotel in the Delta. Walking distance to Ground Zero. Everyone stays here.',
      isPublic: true,
    },
    {
      name: 'The Big Muddy Inn',
      city: 'Natchez',
      state: 'MS',
      rateLow: 12500,
      rateHigh: 20000,
      roomCount: 6,
      amenities: ['wifi', 'parking', 'bar', 'breakfast', 'live_music'],
      bandFriendly: true,
      bandFriendlyNotes: 'We ARE the band hotel. Artists stay free when performing.',
      sprinterParking: true,
      notes: 'Home base. Artists performing at the Blues Room stay on-site — lodging included in booking deal.',
      isPublic: true,
    },
    {
      name: 'Quest Inn & Suites',
      city: 'Clarksdale',
      state: 'MS',
      rateLow: 6500,
      rateHigh: 9500,
      roomCount: 40,
      amenities: ['wifi', 'parking', 'breakfast'],
      bandFriendly: true,
      bandFriendlyNotes: 'Budget option. Fine for overnight. No frills.',
      sprinterParking: true,
      notes: 'Backup if Shack Up is full. Budget corridor stop.',
      isPublic: true,
    },
    {
      name: 'The Guest House at Graceland',
      city: 'Memphis',
      state: 'TN',
      rateLow: 15000,
      rateHigh: 35000,
      roomCount: 450,
      amenities: ['wifi', 'parking', 'pool', 'restaurant', 'bar', 'shuttle'],
      bandFriendly: true,
      bandFriendlyNotes: 'Professional. Good for artist comfort. Near Beale St.',
      sprinterParking: true,
      notes: 'Higher end Memphis option. Good for headliner acts who expect comfort.',
      isPublic: true,
    },
    {
      name: 'Days Inn Memphis',
      city: 'Memphis',
      state: 'TN',
      rateLow: 7000,
      rateHigh: 12000,
      roomCount: 100,
      amenities: ['wifi', 'parking', 'breakfast'],
      bandFriendly: true,
      bandFriendlyNotes: 'Budget Memphis option. Fine for one night.',
      sprinterParking: true,
      notes: 'Budget corridor stop. Near I-55 for easy access.',
      isPublic: true,
    },
  ]

  // ── NEW: Full Corridor Hotels ──
  const corridorHotels = [
    // ── NEW ORLEANS ──
    {
      name: 'Royal Frenchmen Hotel & Bar',
      city: 'New Orleans',
      state: 'LA',
      address: '700 Frenchmen St, New Orleans, LA 70116',
      rateLow: 13500,
      rateHigh: 28000,
      roomCount: 18,
      amenities: ['wifi', 'parking', 'bar', 'restaurant'],
      bandFriendly: true,
      bandFriendlyNotes: 'On Frenchmen Street. In-house bar. Walking distance to all Frenchmen venues.',
      sprinterParking: true,
      notes: 'Best musician hotel in NOLA. ON Frenchmen Street. Private parking for every guest. In-house bar + restaurant.',
      isPublic: true,
    },
    {
      name: 'India House Hostel',
      city: 'New Orleans',
      state: 'LA',
      address: '124 S Lopez St, New Orleans, LA 70119',
      rateLow: 3500,
      rateHigh: 8000,
      roomCount: 50,
      amenities: ['wifi', 'parking', 'pool', 'kitchen', 'laundry'],
      bandFriendly: true,
      bandFriendlyNotes: 'Budget hostel. Dorms and private rooms. Pool. Kitchen access. Musicians frequent.',
      sprinterParking: true,
      notes: 'Budget NOLA option. Dorms from $35/night, privates from $80. Pool, communal kitchen. Band budget-friendly.',
      isPublic: true,
    },
    {
      name: 'NOPSI Hotel',
      city: 'New Orleans',
      state: 'LA',
      address: '317 Baronne St, New Orleans, LA 70112',
      rateLow: 16000,
      rateHigh: 35000,
      roomCount: 217,
      amenities: ['wifi', 'parking', 'pool', 'restaurant', 'bar', 'gym'],
      bandFriendly: true,
      bandFriendlyNotes: 'Upscale but practical. Free parking. Near Frenchmen via short drive.',
      sprinterParking: true,
      notes: 'Higher-end NOLA option with free parking. Good for headliner comfort. Rooftop pool + bar.',
      isPublic: true,
    },
    // ── BATON ROUGE ──
    {
      name: 'The Cook Hotel at LSU',
      city: 'Baton Rouge',
      state: 'LA',
      address: '3848 W Lakeshore Dr, Baton Rouge, LA 70808',
      rateLow: 10000,
      rateHigh: 18000,
      roomCount: 128,
      amenities: ['wifi', 'parking', 'breakfast', 'gym'],
      bandFriendly: true,
      bandFriendlyNotes: 'Self-parking. 0.76 miles from Varsity Theatre. LSU campus location.',
      sprinterParking: true,
      notes: 'Best BR option for touring. Near Varsity Theatre. Free parking. 9.4 review rating. On LSU campus.',
      isPublic: true,
    },
    {
      name: 'Courtyard by Marriott Baton Rouge Acadian Centre/LSU',
      city: 'Baton Rouge',
      state: 'LA',
      address: '2032 Brightside Dr, Baton Rouge, LA 70820',
      rateLow: 10000,
      rateHigh: 16000,
      roomCount: 149,
      amenities: ['wifi', 'parking', 'breakfast', 'pool'],
      bandFriendly: true,
      bandFriendlyNotes: 'Free parking, free breakfast. 1.6 miles from Varsity Theatre.',
      sprinterParking: true,
      notes: 'Budget-mid BR option. Free breakfast + parking. Short drive to Varsity Theatre.',
      isPublic: true,
    },
    // ── VICKSBURG ──
    {
      name: 'Mulberry, a Wyndham Hotel',
      city: 'Vicksburg',
      state: 'MS',
      address: '4155 Frontage Rd, Vicksburg, MS 39180',
      rateLow: 8000,
      rateHigh: 14000,
      roomCount: 68,
      amenities: ['wifi', 'parking', 'pool', 'bikes'],
      bandFriendly: true,
      bandFriendlyNotes: 'Free private parking. 3 min walk to Convention Center. Pool.',
      sprinterParking: true,
      notes: 'Downtown Vicksburg. Free parking. Pool. Near Bottleneck Blues Bar (casino).',
      isPublic: true,
    },
    // ── JACKSON ──
    {
      name: 'Homewood Suites by Hilton Jackson Fondren',
      city: 'Jackson',
      state: 'MS',
      address: '2535 N State St, Jackson, MS 39216',
      rateLow: 10000,
      rateHigh: 16000,
      roomCount: 91,
      amenities: ['wifi', 'parking', 'breakfast', 'kitchen', 'pool'],
      bandFriendly: true,
      bandFriendlyNotes: 'Fondren District. Free parking. Free breakfast. Evening reception Mon-Thu. Suites with kitchens.',
      sprinterParking: true,
      notes: 'Best Jackson option. Fondren District (restaurants, bars walking distance). Free parking, breakfast, evening reception.',
      isPublic: true,
    },
    {
      name: 'Old Capitol Inn',
      city: 'Jackson',
      state: 'MS',
      address: '226 N State St, Jackson, MS 39201',
      rateLow: 12000,
      rateHigh: 20000,
      roomCount: 24,
      amenities: ['wifi', 'parking', 'breakfast', 'bar', 'rooftop'],
      bandFriendly: true,
      bandFriendlyNotes: 'Boutique downtown. Rooftop bar. Walking distance to Hal & Mal\'s and Martin\'s.',
      sprinterParking: true,
      notes: 'Boutique option downtown Jackson. Rooftop bar. Near Hal & Mal\'s. Good for headliner comfort.',
      isPublic: true,
    },
    // ── GREENVILLE ──
    {
      name: 'Hotel 27 / Greenville Inn & Suites',
      city: 'Greenville',
      state: 'MS',
      address: '211 S Walnut St, Greenville, MS 38701',
      rateLow: 6000,
      rateHigh: 10000,
      roomCount: 40,
      amenities: ['wifi', 'parking'],
      bandFriendly: true,
      bandFriendlyNotes: 'On Walnut Street. Walking distance to Walnut Street Blues Bar.',
      sprinterParking: true,
      notes: 'Downtown Greenville on Walnut Street. Walking distance to blues venues. Budget option.',
      isPublic: true,
    },
    // ── GREENWOOD ──
    {
      name: 'The Alluvian Hotel',
      city: 'Greenwood',
      state: 'MS',
      address: '318 Howard St, Greenwood, MS 38930',
      phone: '662-453-2114',
      rateLow: 15000,
      rateHigh: 30000,
      roomCount: 50,
      amenities: ['wifi', 'parking', 'breakfast', 'spa', 'restaurant', 'gym'],
      bandFriendly: true,
      bandFriendlyNotes: 'Luxury Delta hotel. Valet and street parking. Free breakfast. Spa.',
      sprinterParking: true,
      notes: 'Upscale Greenwood option. 45 rooms + 5 suites + 4 lofts. Giardina\'s Restaurant. Free parking + breakfast. Robert Johnson territory.',
      isPublic: true,
    },
    // ── INDIANOLA ──
    {
      name: 'Hampton Inn Indianola',
      city: 'Indianola',
      state: 'MS',
      address: 'US 82, Indianola, MS 38751',
      rateLow: 9000,
      rateHigh: 14700,
      roomCount: 60,
      amenities: ['wifi', 'parking', 'breakfast', 'pool'],
      bandFriendly: true,
      bandFriendlyNotes: 'On US 82. Free parking. Free hot breakfast. 1.4 miles from B.B. King Museum.',
      sprinterParking: true,
      notes: 'Best Indianola option. Near B.B. King Museum and Club Ebony. Free hot breakfast with waffles.',
      isPublic: true,
    },
    // ── HOLLY SPRINGS ──
    {
      name: 'Wynne House Inn',
      city: 'Holly Springs',
      state: 'MS',
      address: 'Holly Springs, MS 38635',
      rateLow: 10000,
      rateHigh: 18000,
      roomCount: 5,
      amenities: ['wifi', 'parking', 'breakfast'],
      bandFriendly: true,
      bandFriendlyNotes: 'B&B near the Square. Elegant but small. May need Oxford overflow for larger bands.',
      sprinterParking: true,
      notes: 'Historic B&B. Near the Square. Limited rooms — larger bands may need to stay in Oxford (30 min) or Memphis (55 min).',
      isPublic: true,
    },
    // ── TUPELO ──
    {
      name: 'Hotel Tupelo',
      city: 'Tupelo',
      state: 'MS',
      address: 'Tupelo, MS 38801',
      rateLow: 8000,
      rateHigh: 14000,
      roomCount: 60,
      amenities: ['wifi', 'parking', 'breakfast'],
      bandFriendly: true,
      bandFriendlyNotes: 'Budget-friendly. Free parking and breakfast.',
      sprinterParking: true,
      notes: 'Budget Tupelo option. Free parking + breakfast. Near Blue Canoe.',
      isPublic: true,
    },
    // ── OXFORD ──
    {
      name: 'Graduate Oxford',
      city: 'Oxford',
      state: 'MS',
      address: '400 N Lamar Blvd, Oxford, MS 38655',
      rateLow: 12800,
      rateHigh: 29900,
      roomCount: 122,
      amenities: ['wifi', 'parking', 'bar', 'gym', 'rooftop'],
      bandFriendly: true,
      bandFriendlyNotes: 'On the Square. Rooftop bar. Free parking. Pet-friendly.',
      sprinterParking: true,
      notes: 'On the Square. Rooftop bar with panoramic views. Free parking. Walking distance to Proud Larry\'s. Higher end.',
      isPublic: true,
    },
    {
      name: 'La Quinta Inn & Suites Oxford',
      city: 'Oxford',
      state: 'MS',
      address: 'Oxford, MS 38655',
      rateLow: 9500,
      rateHigh: 16000,
      roomCount: 80,
      amenities: ['wifi', 'parking', 'breakfast', 'pool'],
      bandFriendly: true,
      bandFriendlyNotes: 'Budget option. Free parking and breakfast. Pet-friendly.',
      sprinterParking: true,
      notes: 'Budget Oxford option from $95/night. Free parking + breakfast. Short drive to Square.',
      isPublic: true,
    },
  ]

  // Merge existing hotels + new corridor hotels
  const allHotels = [...hotels, ...corridorHotels]

  for (const hotel of allHotels) {
    await prisma.touringHotel.create({
      data: hotel,
    })
  }
  console.log(`Seeded ${allHotels.length} touring hotels (${hotels.length} existing + ${corridorHotels.length} new corridor)`)

  // ── Corridor Cities (13 stops, NOLA to Memphis) ──
  const corridorCities = [
    {
      name: 'New Orleans',
      state: 'LA',
      slug: 'new-orleans-la',
      population: 383997,
      role: 'major_hub',
      corridorOrder: 1,
      driveFromPrevMiles: null,
      driveFromPrevHours: null,
      musicScene: 'World capital of jazz, blues, funk, brass, and second line. Frenchmen Street is the live music epicenter. Hundreds of working musicians. Jazz Fest, French Quarter Fest, Voodoo Fest.',
      logisticsNotes: 'Parking limited on Frenchmen Street. Sprinter vans need paid lots. Load-in restricted hours on some streets. French Quarter = no large vehicles.',
      seasonalNotes: 'Year-round music city. Peak: Jazz Fest (late Apr/May), Mardi Gras (Feb/Mar). Slow: Aug-Sep (hurricane season, heat).',
      isPublic: true,
    },
    {
      name: 'Baton Rouge',
      state: 'LA',
      slug: 'baton-rouge-la',
      population: 227470,
      role: 'stopover',
      corridorOrder: 2,
      driveFromPrevMiles: 80,
      driveFromPrevHours: 1.5,
      musicScene: 'LSU college town energy. Varsity Theatre anchors touring scene. Teddy\'s Juke Joint (Zachary) is the real deal — international blues acts in a farmland juke joint.',
      logisticsNotes: 'Easy Sprinter access. Hotels with free parking near LSU. I-10/I-12 hub.',
      seasonalNotes: 'LSU football season (Sep-Nov) fills hotels. Summer slower.',
      isPublic: true,
    },
    {
      name: 'Natchez',
      state: 'MS',
      slug: 'natchez-ms',
      population: 14520,
      role: 'home_base',
      corridorOrder: 3,
      driveFromPrevMiles: 120,
      driveFromPrevHours: 2,
      musicScene: 'Home base. The Big Muddy Inn Blues Room. Natchez Music Festival. Historic blues and folk roots. Under the Hill district.',
      logisticsNotes: 'Small town, easy parking. Under the Hill district for riverfront venues. Sprinter access excellent.',
      seasonalNotes: 'Peak: Spring Pilgrimage (Mar-Apr), Fall Pilgrimage (Oct). Slow: Jul-Aug (heat). Festival weekends book up.',
      isPublic: true,
    },
    {
      name: 'Vicksburg',
      state: 'MS',
      slug: 'vicksburg-ms',
      population: 22507,
      role: 'stopover',
      corridorOrder: 4,
      driveFromPrevMiles: 70,
      driveFromPrevHours: 1,
      musicScene: 'Casino-anchored blues scene (Bottleneck Blues Bar at Ameristar). Key City Brewery for craft/acoustic acts. Mississippi Blues Trail markers. Annual Music & Culture Festival.',
      logisticsNotes: 'Casino parking lot handles any vehicle. Downtown has street parking. I-20 access.',
      seasonalNotes: 'Casino traffic year-round. Downtown events seasonal.',
      isPublic: true,
    },
    {
      name: 'Jackson',
      state: 'MS',
      slug: 'jackson-ms',
      population: 153701,
      role: 'talent_supply',
      corridorOrder: 5,
      driveFromPrevMiles: 100,
      driveFromPrevHours: 2,
      musicScene: 'Bobby Rush, Grady Champion, Jarekus Singleton territory. Hal & Mal\'s is the anchor. F. Jones Corner for authentic late-night blues. Fondren District for dining + nightlife. Blue Monday jams.',
      logisticsNotes: 'Fondren District walkable. Downtown venues have parking. I-55/I-20 crossroads.',
      seasonalNotes: 'Year-round. Fondren First Thursday events monthly.',
      isPublic: true,
    },
    {
      name: 'Greenville',
      state: 'MS',
      slug: 'greenville-ms',
      population: 27446,
      role: 'delta_gateway',
      corridorOrder: 6,
      driveFromPrevMiles: 130,
      driveFromPrevHours: 2,
      musicScene: 'Eden Brent territory. Walnut Street Blues Bar for local blues. The Blue Biscuit for juke joint atmosphere. Delta blues roots deep here.',
      logisticsNotes: 'Small Delta town. Easy parking everywhere. US 82 access.',
      seasonalNotes: 'Delta Hot Tamale Festival (Oct). Mississippi Delta Blues and Heritage Festival.',
      isPublic: true,
    },
    {
      name: 'Greenwood',
      state: 'MS',
      slug: 'greenwood-ms',
      population: 13092,
      role: 'cultural_landmark',
      corridorOrder: 7,
      driveFromPrevMiles: 35,
      driveFromPrevHours: 0.67,
      musicScene: 'Robert Johnson crossroads territory. Baptist Town is a living blues museum. Robert Johnson buried at Little Zion Missionary Baptist Church. Guitar exhibit at museum (summer). More pilgrimage site than music scene currently.',
      logisticsNotes: 'Small town. Alluvian Hotel is the upscale anchor. Easy parking.',
      seasonalNotes: 'America at the Crossroads guitar exhibit (summer). Quiet otherwise.',
      isPublic: true,
    },
    {
      name: 'Indianola',
      state: 'MS',
      slug: 'indianola-ms',
      population: 9549,
      role: 'cultural_landmark',
      corridorOrder: 8,
      driveFromPrevMiles: 25,
      driveFromPrevHours: 0.5,
      musicScene: 'B.B. King Museum and Club Ebony. Legendary. Club Ebony est. 1948 — B.B. King, Ray Charles, Count Basie played here. Renovated 2023. Hologram experience 2025. Pilgrimage destination.',
      logisticsNotes: 'Small Delta town. US 82 access. Easy parking at museum/club.',
      seasonalNotes: 'B.B. King Homecoming Festival. Museum open Thu-Sat. Special events at Club Ebony.',
      isPublic: true,
    },
    {
      name: 'Clarksdale',
      state: 'MS',
      slug: 'clarksdale-ms',
      population: 14800,
      role: 'major_hub',
      corridorOrder: 9,
      driveFromPrevMiles: 60,
      driveFromPrevHours: 1,
      musicScene: 'Ground Zero Blues Club (Morgan Freeman co-owned). Red\'s Lounge (real juke joint). Cat Head Delta Blues & Folk Art. Juke Joint Festival (April). Dozens of working blues musicians. THE Delta blues destination.',
      logisticsNotes: 'Downtown walkable between venues. Shack Up Inn for lodging. Delta Ave is the strip. Roger Stolle at Cat Head is the booking connector.',
      seasonalNotes: 'Juke Joint Festival (April) is THE event. Slow Jun-Aug (heat). Festival brings 5,000+ visitors.',
      keyContacts: [{ name: 'Roger Stolle', role: 'Cat Head / Booking Connector', email: 'roger@cathead.biz' }],
      isPublic: true,
    },
    {
      name: 'Holly Springs',
      state: 'MS',
      slug: 'holly-springs-ms',
      population: 7621,
      role: 'cultural_landmark',
      corridorOrder: 10,
      driveFromPrevMiles: 60,
      driveFromPrevHours: 1,
      musicScene: 'Birthplace of Hill Country Blues. R.L. Burnside, Junior Kimbrough territory. Burnside Bar and Grill (Duwayne Burnside runs it in Kimbrough\'s old juke joint). Cedric Burnside, Lightnin\' Malcolm from here.',
      logisticsNotes: 'Small town. Limited lodging — may need Oxford (30 min) or Memphis (55 min). Easy parking.',
      seasonalNotes: 'Live blues weekly at Burnside Bar and Grill. BBQ + blues format.',
      isPublic: true,
    },
    {
      name: 'Tupelo',
      state: 'MS',
      slug: 'tupelo-ms',
      population: 38300,
      role: 'stopover',
      corridorOrder: 11,
      driveFromPrevMiles: 55,
      driveFromPrevHours: 1,
      musicScene: 'Paul Thorn territory. Elvis birthplace. Blue Canoe is the live music anchor (hosted Gary Clark Jr., Alabama Shakes). Backline Music Hall newest venue. Cadence Bank Arena for arena acts.',
      logisticsNotes: 'Easy Sprinter access. Hotels on I-22 corridor. Good parking everywhere.',
      seasonalNotes: 'Tupelo Elvis Festival (June). Year-round music at Blue Canoe.',
      isPublic: true,
    },
    {
      name: 'Oxford',
      state: 'MS',
      slug: 'oxford-ms',
      population: 28122,
      role: 'stopover',
      corridorOrder: 12,
      driveFromPrevMiles: 50,
      driveFromPrevHours: 1,
      musicScene: 'University town (Ole Miss). Proud Larry\'s (20+ years, 300 cap). The Lyric Oxford (1913 theater, 1,000 cap). Square is the nightlife district. City Grocery Bar for cocktails.',
      logisticsNotes: 'The Square is walkable. No parking lot at Lyric — street parking only. Hotels near campus have free parking.',
      seasonalNotes: 'Ole Miss football season (Sep-Nov) books up. Double Decker Arts Festival (April). Summer quieter.',
      isPublic: true,
    },
    {
      name: 'Memphis',
      state: 'TN',
      slug: 'memphis-tn',
      population: 633104,
      role: 'major_hub',
      corridorOrder: 13,
      driveFromPrevMiles: 80,
      driveFromPrevHours: 1.5,
      musicScene: 'Blues, soul, rock capital. Beale Street (B.B. King\'s, Rum Boogie, Blues City Cafe). Overton Square (Lafayette\'s Music Room). Midtown (Hi-Tone, Young Avenue Deli, Bar DKDC). Crosstown Arts. Sun Studio. Stax Museum.',
      logisticsNotes: 'Beale Street restricted hours for large vehicles. Overton Square and Midtown easier for Sprinter. I-55/I-40 crossroads.',
      seasonalNotes: 'Memphis in May (Beale St Music Fest, BBQ Fest) is peak. Year-round tourism. Note: Railgarten CLOSED (late 2025).',
      isPublic: true,
    },
  ]

  for (const city of corridorCities) {
    await prisma.corridorCity.upsert({
      where: { slug: city.slug },
      update: { ...city },
      create: { ...city },
    })
  }
  console.log(`Seeded ${corridorCities.length} corridor cities`)

  // ── Touring Restaurants ──
  const restaurants = [
    // ── NEW ORLEANS ──
    {
      name: 'Dat Dog',
      city: 'New Orleans',
      state: 'LA',
      address: '601 Frenchmen St, New Orleans, LA 70116',
      cuisine: 'Hot dogs',
      priceRange: '$',
      lateNight: true,
      closingTime: '3:00 AM (Fri-Sat), Midnight (weekdays)',
      musicianFriendly: true,
      musicianNotes: 'On Frenchmen Street. Open late. Budget-friendly. 30+ toppings. Vegetarian options. Perfect post-show fuel.',
      isPublic: true,
    },
    {
      name: 'Three Muses',
      city: 'New Orleans',
      state: 'LA',
      address: '536 Frenchmen St, New Orleans, LA 70116',
      cuisine: 'Small plates / Tapas',
      priceRange: '$$',
      lateNight: true,
      closingTime: '11:00 PM',
      musicianFriendly: true,
      musicianNotes: 'Live jazz + innovative small plates. Cozy. On Frenchmen. Good for a nicer post-show meal.',
      isPublic: true,
    },
    {
      name: 'Marigny Brasserie',
      city: 'New Orleans',
      state: 'LA',
      address: '640 Frenchmen St, New Orleans, LA 70116',
      cuisine: 'Cajun/Creole',
      priceRange: '$$',
      lateNight: true,
      closingTime: 'Midnight',
      musicianFriendly: true,
      musicianNotes: 'Cajun/Creole menu. Handcrafted cocktails. Live big band music. Frenchmen Street.',
      isPublic: true,
    },
    // ── BATON ROUGE ──
    {
      name: "Nancy's Kitchen at Teddy's",
      city: 'Zachary',
      state: 'LA',
      address: '16999 Old Scenic Hwy, Zachary, LA 70791',
      cuisine: 'Soul food',
      priceRange: '$',
      lateNight: true,
      closingTime: 'Closes with Teddy\'s (late)',
      musicianFriendly: true,
      musicianNotes: 'Inside Teddy\'s Juke Joint. Some of the best food in the region. Soul food while listening to blues. The real deal.',
      isPublic: true,
    },
    // ── VICKSBURG ──
    {
      name: 'The Biscuit Company',
      city: 'Vicksburg',
      state: 'MS',
      address: 'Vicksburg, MS 39183',
      cuisine: 'Southern / Comfort food',
      priceRange: '$',
      lateNight: false,
      closingTime: '9:00 PM',
      musicianFriendly: true,
      musicianNotes: 'Downtown Vicksburg. Southern comfort food. Good for pre-show dinner.',
      isPublic: true,
    },
    // ── JACKSON ──
    {
      name: 'Fondren Public',
      city: 'Jackson',
      state: 'MS',
      address: '2757 Old Canton Rd, Jackson, MS 39216',
      cuisine: 'Bar food / Southern',
      priceRange: '$',
      lateNight: true,
      closingTime: '2:00 AM (Fri-Sat), Midnight (weekdays)',
      musicianFriendly: true,
      musicianNotes: 'Fondren District. Live music. Locally distilled spirits. Bar bites: fried pickles, tacos, personal pizzas. Open late.',
      isPublic: true,
    },
    {
      name: 'Names & Faces Lounge',
      city: 'Jackson',
      state: 'MS',
      address: 'Jackson, MS 39201',
      cuisine: 'Southern / Catfish',
      priceRange: '$',
      lateNight: true,
      closingTime: '2:00 AM',
      musicianFriendly: true,
      musicianNotes: 'Catfish, tacos, hot music until 2 AM. Real Jackson late-night spot.',
      isPublic: true,
    },
    // ── GREENVILLE ──
    {
      name: "Do's Eat Place",
      city: 'Greenville',
      state: 'MS',
      address: '502 Nelson St, Greenville, MS 38701',
      cuisine: 'Steak / Southern',
      priceRange: '$$',
      lateNight: false,
      closingTime: '9:00 PM',
      musicianFriendly: true,
      musicianNotes: 'Legendary Delta steaks. Cash only. Iconic Greenville institution. Pre-show dinner spot.',
      isPublic: true,
    },
    // ── CLARKSDALE ──
    {
      name: 'Stone Pony Pizza',
      city: 'Clarksdale',
      state: 'MS',
      address: '226 Delta Ave, Clarksdale, MS 38614',
      phone: '662-624-7669',
      cuisine: 'Pizza',
      priceRange: '$',
      lateNight: true,
      closingTime: '10:00 PM',
      musicianFriendly: true,
      musicianNotes: 'On Delta Ave near Ground Zero. Open Mon-Sat 11am-10pm. Good pre/post-show pizza. Musician hangout.',
      isPublic: true,
    },
    {
      name: "Abe's Bar-B-Q",
      city: 'Clarksdale',
      state: 'MS',
      address: '616 State St, Clarksdale, MS 38614',
      phone: '662-624-9947',
      cuisine: 'BBQ',
      priceRange: '$',
      lateNight: false,
      closingTime: '8:30 PM (Mon-Sat)',
      musicianFriendly: true,
      musicianNotes: 'Clarksdale institution. Open since 1924. Best BBQ in the Delta. Pre-show essential. Mon-Sat 10am-8:30pm.',
      isPublic: true,
    },
    // ── TUPELO ──
    {
      name: 'Blue Canoe (Kitchen)',
      city: 'Tupelo',
      state: 'MS',
      address: '2006 N Gloster St, Tupelo, MS 38804',
      phone: '662-269-2642',
      cuisine: 'Bar food / Burgers',
      priceRange: '$',
      lateNight: true,
      closingTime: 'Late (bar hours)',
      musicianFriendly: true,
      musicianNotes: 'Kitchen at the venue. Top 10 burgers in MS. 100+ beers (35 on tap). Late night food service. Eat where you play.',
      isPublic: true,
    },
    // ── OXFORD ──
    {
      name: 'Ajax Diner',
      city: 'Oxford',
      state: 'MS',
      address: '118 Courthouse Sq, Oxford, MS 38655',
      cuisine: 'Southern comfort',
      priceRange: '$',
      lateNight: false,
      closingTime: '9:00 PM',
      musicianFriendly: true,
      musicianNotes: 'On the Square. Southern comfort food institution. Budget-friendly. Mon-Sat 11am-9pm. Pre-show dinner.',
      isPublic: true,
    },
    {
      name: 'City Grocery Bar',
      city: 'Oxford',
      state: 'MS',
      address: '152 Courthouse Sq, Oxford, MS 38655',
      cuisine: 'Bar / Cocktails',
      priceRange: '$$',
      lateNight: true,
      closingTime: 'Late',
      musicianFriendly: true,
      musicianNotes: 'Upstairs bar overlooking the Square. Balcony seating. Cocktails + bar menu. Post-show hangout. The spot in Oxford.',
      isPublic: true,
    },
    // ── MEMPHIS ──
    {
      name: "Lafayette's Music Room (Kitchen)",
      city: 'Memphis',
      state: 'TN',
      address: '2119 Madison Ave, Memphis, TN 38104',
      cuisine: 'Southern comfort / Pizza',
      priceRange: '$$',
      lateNight: true,
      closingTime: 'Late (venue hours)',
      musicianFriendly: true,
      musicianNotes: 'Kitchen at the venue. Mac and cheese, wood-fired pizza, made-from-scratch desserts. Live music every night. Eat where you play. Overton Square.',
      isPublic: true,
    },
    {
      name: 'Young Avenue Deli',
      city: 'Memphis',
      state: 'TN',
      address: '2119 Young Ave, Memphis, TN 38104',
      cuisine: 'Deli / Bar food',
      priceRange: '$',
      lateNight: true,
      closingTime: 'Late (bar hours)',
      musicianFriendly: true,
      musicianNotes: 'Cooper-Young neighborhood. Full-service late night dining. Live music. Pool tables. Perfect post-show spot.',
      isPublic: true,
    },
  ]

  for (const restaurant of restaurants) {
    await prisma.touringRestaurant.create({
      data: restaurant,
    })
  }
  console.log(`Seeded ${restaurants.length} touring restaurants`)

  // ── Corridor Route: Delta Run ──
  const route = await prisma.tourRoute.create({
    data: {
      name: 'Delta Run: Natchez → Clarksdale → Memphis',
      slug: 'delta-run-natchez-clarksdale-memphis',
      description: 'The signature Big Muddy corridor. 292 miles, 3 shows, 2 nights. Blues Room (Natchez) → Ground Zero (Clarksdale) → Lafayette\'s (Memphis). The ecosystem multiplier route — every show feeds recordings, radio, magazine, directory.',
      totalMiles: 292,
      estimatedDriveHours: 5,
      budgetLowCents: 320000,
      budgetMidCents: 840000,
      budgetHighCents: 1980000,
      budgetBreakdown: {
        low: { fuel: 100, lodging: 200, perDiem: 225, musicians: 1200, headliner: 900, sound: 300, promo: 100, contingency: 175 },
        mid: { fuel: 150, lodging: 400, perDiem: 375, musicians: 2400, headliner: 3000, sound: 900, promo: 500, contingency: 675 },
        high: { fuel: 200, lodging: 800, perDiem: 600, musicians: 3600, headliner: 9000, sound: 1500, promo: 2000, contingency: 2100 },
      },
      revenueEstimate: {
        door: 3600,
        bar: 1200,
        contentValue: 2000,
        innOccupancyLift: 1500,
        total: 8300,
        note: 'Standalone touring loses money. Ecosystem multiplier makes it break even.',
      },
      bandSize: 5,
      seasonRecommendation: 'Best: Mar-May, Sep-Nov. Juke Joint Festival (April) in Clarksdale is peak. Avoid Jul-Aug (heat).',
      notes: 'Signature route. Start here for all new touring acts. 3 shows in 3 days. Sprinter van, 5 people.',
      isPublic: true,
    },
  })

  // Link stops to route
  const bluesRoom = await prisma.touringVenue.findUnique({ where: { slug: 'blues-room-natchez' } })
  const groundZero = await prisma.touringVenue.findUnique({ where: { slug: 'ground-zero-clarksdale' } })
  const lafayettes = await prisma.touringVenue.findUnique({ where: { slug: 'lafayettes-memphis' } })
  const bigMuddyInn = await prisma.touringHotel.findFirst({ where: { name: 'The Big Muddy Inn' } })
  const shackUp = await prisma.touringHotel.findFirst({ where: { name: 'Shack Up Inn' } })

  const stops = [
    {
      routeId: route.id,
      venueId: bluesRoom?.id,
      hotelId: bigMuddyInn?.id,
      stopOrder: 1,
      city: 'Natchez',
      state: 'MS',
      nightsStay: 0,
      driveFromPrevMiles: 0,
      driveFromPrevHours: 0,
      notes: 'Home base. Show at Blues Room. Artists stay at the Inn.',
    },
    {
      routeId: route.id,
      venueId: groundZero?.id,
      hotelId: shackUp?.id,
      stopOrder: 2,
      city: 'Clarksdale',
      state: 'MS',
      nightsStay: 1,
      driveFromPrevMiles: 215,
      driveFromPrevHours: 3.5,
      notes: 'Delta stop. Show at Ground Zero. Stay at Shack Up Inn.',
    },
    {
      routeId: route.id,
      venueId: lafayettes?.id,
      hotelId: null,
      stopOrder: 3,
      city: 'Memphis',
      state: 'TN',
      nightsStay: 1,
      driveFromPrevMiles: 77,
      driveFromPrevHours: 1.5,
      notes: 'Memphis finale. Show at Lafayette\'s. Optional overnight or drive home.',
    },
  ]

  for (const stop of stops) {
    await prisma.tourRouteStop.create({ data: stop })
  }
  console.log(`Seeded Delta Run route with ${stops.length} stops`)

  console.log('Touring seed complete.')
}

seedTouring()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e)
    prisma.$disconnect()
    process.exit(1)
  })
