#!/usr/bin/env node
// scripts/ai/gemini-batch.mjs
//
// Standalone Gemini batch dispatcher. Reads a JSON batch file, runs every task
// in parallel against Vertex AI Gemini, writes outputs to disk.
//
// Usage:
//   node scripts/ai/gemini-batch.mjs <path/to/batch.json>
//   node scripts/ai/gemini-batch.mjs scripts/ai/batches/voice-docs.json
//
// Reuses GOOGLE_APPLICATION_CREDENTIALS_JSON from apps/web/.env.local — no new
// secrets needed. Safe to run from CI or locally.
//
// Batch file shape:
//   {
//     "model": "gemini-2.5-flash" | "gemini-3.1-pro",
//     "concurrency": 5,
//     "tasks": [
//       {
//         "id": "voice-inn",
//         "outputPath": "docs/voice/inn.md",
//         "system": "You are...",
//         "prompt": "Write...",
//         "maxTokens": 4096,
//         "temperature": 0.7
//       }
//     ]
//   }

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import dotenv from 'dotenv';
import { GoogleAuth } from 'google-auth-library';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '../..');

// Load env from apps/web/.env.local
dotenv.config({ path: path.join(REPO_ROOT, 'apps/web/.env.local') });

const VERTEX_PROJECT_ID = process.env.VERTEX_PROJECT_ID || 'bigmuddy-ff651';
const VERTEX_LOCATION_PRIMARY = 'us-central1'; // matches lib/ai-models.ts callGemini
const DEFAULT_MAX_TOKENS = 4096;
const DEFAULT_TEMPERATURE = 0.7;
const DEFAULT_CONCURRENCY = 5;

if (!process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON) {
  console.error('ERROR: GOOGLE_APPLICATION_CREDENTIALS_JSON not set in apps/web/.env.local');
  process.exit(1);
}

const credsRaw = process.env.GOOGLE_APPLICATION_CREDENTIALS_JSON;
let credsJson;
try {
  // dotenv preserves real newlines from .env.local. The Vercel env var
  // contains a private_key with literal \n which dotenv interprets as actual
  // newlines — these are invalid JSON control chars. Re-escape them.
  const fixed = credsRaw
    .replace(/\r\n/g, '\\n')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  credsJson = JSON.parse(fixed);
} catch (e) {
  console.error('ERROR: GOOGLE_APPLICATION_CREDENTIALS_JSON is not valid JSON:', e.message);
  process.exit(1);
}

const auth = new GoogleAuth({
  credentials: credsJson,
  scopes: ['https://www.googleapis.com/auth/cloud-platform'],
});

let cachedToken = null;
let tokenExpiry = 0;

async function getToken() {
  if (cachedToken && Date.now() < tokenExpiry - 60_000) return cachedToken;
  const client = await auth.getClient();
  const t = await client.getAccessToken();
  cachedToken = t.token;
  tokenExpiry = (t.res?.data?.expires_in ? Date.now() + t.res.data.expires_in * 1000 : Date.now() + 30 * 60_000);
  return cachedToken;
}

async function callGemini({ model, system, prompt, maxTokens, temperature }) {
  const token = await getToken();
  const endpoint = `https://${VERTEX_LOCATION_PRIMARY}-aiplatform.googleapis.com/v1/projects/${VERTEX_PROJECT_ID}/locations/${VERTEX_LOCATION_PRIMARY}/publishers/google/models/${model}:generateContent`;

  const body = {
    contents: [
      { role: 'user', parts: [{ text: prompt }] },
    ],
    systemInstruction: { parts: [{ text: system }] },
    generationConfig: {
      maxOutputTokens: maxTokens || DEFAULT_MAX_TOKENS,
      temperature: temperature || DEFAULT_TEMPERATURE,
    },
  };

  const res = await fetch(endpoint, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(120_000),
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Gemini ${res.status}: ${errText.slice(0, 500)}`);
  }

  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text || '';
  const usage = data.usageMetadata || {};
  return {
    text,
    promptTokens: usage.promptTokenCount || 0,
    completionTokens: usage.candidatesTokenCount || 0,
    totalTokens: usage.totalTokenCount || 0,
  };
}

async function runTask(task, model, idx, total) {
  const start = Date.now();
  console.log(`[${idx + 1}/${total}] START: ${task.id} → ${task.outputPath}`);
  try {
    const result = await callGemini({
      model: task.model || model,
      system: task.system,
      prompt: task.prompt,
      maxTokens: task.maxTokens,
      temperature: task.temperature,
    });
    const outputPath = path.join(REPO_ROOT, task.outputPath);
    await fs.mkdir(path.dirname(outputPath), { recursive: true });
    const header = task.skipHeader ? '' : `<!--\n  Generated by scripts/ai/gemini-batch.mjs on ${new Date().toISOString()}\n  Task: ${task.id}\n  Model: ${task.model || model}\n  Tokens: ${result.totalTokens} (prompt ${result.promptTokens} + completion ${result.completionTokens})\n-->\n\n`;
    await fs.writeFile(outputPath, header + result.text, 'utf8');
    const elapsed = ((Date.now() - start) / 1000).toFixed(1);
    console.log(`[${idx + 1}/${total}] DONE: ${task.id} (${elapsed}s, ${result.totalTokens} tok)`);
    return { id: task.id, success: true, tokens: result.totalTokens, elapsedMs: Date.now() - start };
  } catch (e) {
    const elapsed = ((Date.now() - start) / 1000).toFixed(1);
    console.error(`[${idx + 1}/${total}] FAIL: ${task.id} (${elapsed}s) — ${e.message}`);
    return { id: task.id, success: false, error: e.message, elapsedMs: Date.now() - start };
  }
}

async function pmap(items, concurrency, fn) {
  const results = new Array(items.length);
  let cursor = 0;
  async function worker() {
    while (true) {
      const i = cursor++;
      if (i >= items.length) return;
      results[i] = await fn(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(concurrency, items.length) }, () => worker()));
  return results;
}

async function main() {
  const batchPath = process.argv[2];
  if (!batchPath) {
    console.error('Usage: node scripts/ai/gemini-batch.mjs <path/to/batch.json>');
    process.exit(1);
  }

  const batchFile = path.resolve(batchPath);
  const raw = await fs.readFile(batchFile, 'utf8');
  const batch = JSON.parse(raw);

  const model = batch.model || 'gemini-2.5-flash';
  const concurrency = batch.concurrency || DEFAULT_CONCURRENCY;
  const tasks = batch.tasks || [];

  console.log(`\n=== Gemini Batch Dispatcher ===`);
  console.log(`Batch file: ${batchFile}`);
  console.log(`Model: ${model}`);
  console.log(`Concurrency: ${concurrency}`);
  console.log(`Tasks: ${tasks.length}`);
  console.log(`Vertex project: ${VERTEX_PROJECT_ID}`);
  console.log(`Vertex location: ${VERTEX_LOCATION_PRIMARY}\n`);

  const start = Date.now();
  const results = await pmap(tasks, concurrency, (t, i) => runTask(t, model, i, tasks.length));
  const elapsed = ((Date.now() - start) / 1000).toFixed(1);

  const succeeded = results.filter((r) => r.success);
  const failed = results.filter((r) => !r.success);
  const totalTokens = succeeded.reduce((sum, r) => sum + (r.tokens || 0), 0);

  console.log(`\n=== Batch Complete ===`);
  console.log(`Total: ${tasks.length} | Succeeded: ${succeeded.length} | Failed: ${failed.length}`);
  console.log(`Total tokens: ${totalTokens.toLocaleString()}`);
  console.log(`Elapsed: ${elapsed}s`);

  if (failed.length > 0) {
    console.log(`\nFailed tasks:`);
    failed.forEach((f) => console.log(`  - ${f.id}: ${f.error}`));
    process.exit(1);
  }
}

main().catch((e) => {
  console.error('FATAL:', e);
  process.exit(1);
});
